// _stele_setup.ts (auto-generated by @stele/backend-typescript; do not edit)
//
// Vitest setup hook for Stele assertion-failure witness propagation.
//
// Hooks `afterEach` so `SteleAssertionFailed.witness` is appended to
// `task.meta.steleWitnesses`. Test runners and the `stele check` test runner
// adapter read these witnesses to populate `ViolationCause.failure_witness`
// per EP07.
//
// To wire this into your project's `vitest.config.ts`, add:
//
//   import { defineConfig } from "vitest/config";
//   export default defineConfig({
//     test: {
//       setupFiles: ["./tests/contract/_stele_setup.ts"],
//     },
//   });
//
// Without the setup wiring, `SteleAssertionFailed` still surfaces as a
// vitest test failure with the witness on the error object; `stele check`
// will fall back to extracting witnesses from rejection-error metadata.

import { afterEach } from "vitest";
import { SteleAssertionFailed, type FailureWitness } from "./_stele_runtime.js";

type TaskWithMeta = {
  meta?: { steleWitnesses?: FailureWitness[] } & Record<string, unknown>;
  result?: { state?: string; errors?: unknown[] } & Record<string, unknown>;
};

afterEach((context) => {
  const task = (context as unknown as { task?: TaskWithMeta }).task;
  if (task === undefined || task.result === undefined) {
    return;
  }
  const errors = task.result.errors;
  if (!Array.isArray(errors) || errors.length === 0) {
    return;
  }
  const meta = (task.meta ?? (task.meta = {})) as { steleWitnesses?: FailureWitness[] } & Record<string, unknown>;
  if (!Array.isArray(meta.steleWitnesses)) {
    meta.steleWitnesses = [];
  }
  for (const error of errors) {
    if (error instanceof SteleAssertionFailed) {
      meta.steleWitnesses.push(error.witness);
    } else if (
      error !== null &&
      typeof error === "object" &&
      "name" in error &&
      (error as { name?: unknown }).name === "SteleAssertionFailed" &&
      "witness" in error
    ) {
      meta.steleWitnesses.push((error as { witness: FailureWitness }).witness);
    }
  }
});
