import { mkdir, writeFile } from "node:fs/promises";
import { dirname, join, resolve } from "node:path";
import { loadContract, type AstNode, type Contract } from "@stele/core";
import { loadConfig } from "../config/loadConfig.js";
import { validateOutputPath } from "../utils/output-path.js";

export type DocOptions = {
  format?: "markdown" | "html";
  output?: string;
};

export async function runDoc(projectDir: string, options: DocOptions): Promise<void> {
  const config = await loadConfig(projectDir);
  const contract = await loadContract(resolve(projectDir, config.entry));

  let content: string;

  if (options.format === "html") {
    content = generateHtml(contract);
  } else {
    content = generateMarkdown(contract);
  }

  const outputDir = options.output ?? resolve(projectDir, "docs", "contract");
  const filename = options.format === "html" ? "index.html" : "contract.md";
  const outputPath = validateOutputPath(projectDir, join(outputDir, filename));

  await mkdir(dirname(outputPath), { recursive: true });
  await writeFile(outputPath, content, "utf8");

  process.stdout.write(`[stele] Contract documentation written to ${filename}.\n`);
}

function formatNode(node: AstNode): string {
  switch (node.kind) {
    case "identifier":
      return node.value;
    case "keyword":
      return `:${node.value}`;
    case "string":
      return node.value;
    case "number":
      return node.raw;
    case "list":
      return `(${node.head} ${node.items.map(formatNode).join(" ")})`;
  }
}

function generateMarkdown(contract: Contract): string {
  const lines: string[] = [];
  lines.push("# Contract Documentation");
  lines.push("");
  lines.push(`Generated by Stele. Covers ${contract.invariants.length} invariants.`);
  lines.push("");

  for (const inv of contract.invariants) {
    lines.push(`## ${inv.id}`);
    lines.push("");
    lines.push("| Field | Value |");
    lines.push("|-------|-------|");
    lines.push(`| Severity | ${inv.severity} |`);
    lines.push(`| Description | ${inv.description} |`);
    if (inv.category) {
      lines.push(`| Category | ${formatNode(inv.category.valueNode)} |`);
    }
    if (inv.rationale) {
      lines.push(`| Rationale | ${formatNode(inv.rationale.valueNode)} |`);
    }
    if (inv.since) {
      lines.push(`| Since | ${formatNode(inv.since.valueNode)} |`);
    }
    lines.push("");
  }

  return lines.join("\n");
}

function escapeHtml(s: string): string {
  return s.replaceAll("&", "&amp;").replaceAll("<", "&lt;").replaceAll(">", "&gt;").replaceAll('"', "&quot;").replaceAll("'", "&#x27;");
}

function generateHtml(contract: Contract): string {
  const invariants = contract.invariants;
  const severities = uniqueString(invariants.map((i) => i.severity));
  const categories = uniqueString(invariants.map((i) => (i.category ? formatNode(i.category.valueNode) : "none")));

  const rows = invariants
    .map((inv) => {
      const cat = inv.category ? formatNode(inv.category.valueNode) : "none";
      const sev = inv.severity;
      const desc = inv.description ?? "";
      const rationale = inv.rationale ? formatNode(inv.rationale.valueNode) : "";
      const code = inv.assertExpression ? escapeHtml(formatNode(inv.assertExpression)) : "";
      return `<tr class="inv-row" data-severity="${escapeHtml(sev)}" data-category="${escapeHtml(cat)}">
<td><a href="#${escapeHtml(inv.id)}">${escapeHtml(inv.id)}</a></td>
<td><span class="badge badge-${escapeHtml(sev.toLowerCase())}">${escapeHtml(sev)}</span></td>
<td>${escapeHtml(cat)}</td>
<td>${escapeHtml(desc)}</td>
</tr>`;
    })
    .join("\n");

  const detailSections = invariants
    .map((inv) => {
      const cat = inv.category ? formatNode(inv.category.valueNode) : "none";
      const sev = inv.severity;
      const desc = inv.description ?? "";
      const rationale = inv.rationale ? formatNode(inv.rationale.valueNode) : "";
      const code = inv.assertExpression ? escapeHtml(formatNode(inv.assertExpression)) : "";
      return `<section id="${escapeHtml(inv.id)}" class="detail" data-severity="${escapeHtml(sev)}" data-category="${escapeHtml(cat)}">
<h2>${escapeHtml(inv.id)} <span class="badge badge-${escapeHtml(sev.toLowerCase())}">${escapeHtml(sev)}</span></h2>
<p><strong>Category:</strong> ${escapeHtml(cat)}</p>
<p><strong>Description:</strong> ${escapeHtml(desc)}</p>
${rationale ? `<p><strong>Rationale:</strong> ${escapeHtml(rationale)}</p>` : ""}
${code ? `<pre class="code-block">${code}</pre>` : ""}
</section>`;
    })
    .join("\n");

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Contract Documentation</title>
<style>
  * { margin: 0; padding: 0; box-sizing: border-box; }
  body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif; line-height: 1.6; color: #1a1a1a; background: #fafafa; padding: 2rem; max-width: 1200px; margin: 0 auto; }
  h1 { font-size: 1.8rem; margin-bottom: 0.5rem; }
  .subtitle { color: #666; margin-bottom: 1.5rem; }
  .filters { display: flex; gap: 1rem; margin-bottom: 1.5rem; flex-wrap: wrap; align-items: center; }
  .filters input, .filters select { padding: 0.4rem 0.8rem; border: 1px solid #ddd; border-radius: 4px; font-size: 0.9rem; }
  .filters input { flex: 1; min-width: 200px; }
  table { width: 100%; border-collapse: collapse; background: #fff; border-radius: 8px; overflow: hidden; box-shadow: 0 1px 3px rgba(0,0,0,0.1); }
  th, td { padding: 0.75rem 1rem; text-align: left; border-bottom: 1px solid #eee; }
  th { background: #f5f5f5; font-weight: 600; font-size: 0.85rem; text-transform: uppercase; color: #666; }
  td a { color: #0066cc; text-decoration: none; }
  td a:hover { text-decoration: underline; }
  .badge { display: inline-block; padding: 0.2rem 0.6rem; border-radius: 12px; font-size: 0.75rem; font-weight: 600; text-transform: uppercase; }
  .badge-critical { background: #fee; color: #c00; }
  .badge-high { background: #fffa; color: #c60; }
  .badge-medium { background: #eff; color: #60c; }
  .badge-low { background: #efe; color: #060; }
  .inv-row { cursor: pointer; transition: background 0.15s; }
  .inv-row:hover { background: #f8f8f8; }
  .inv-row.hidden { display: none; }
  .detail { margin-top: 2rem; padding: 1.5rem; background: #fff; border-radius: 8px; box-shadow: 0 1px 3px rgba(0,0,0,0.1); }
  .detail h2 { margin-bottom: 1rem; }
  .detail .badge { float: right; }
  pre.code-block { background: #f5f5f5; padding: 1rem; border-radius: 4px; overflow-x: auto; font-size: 0.85rem; margin-top: 1rem; }
  .detail.hidden { display: none; }
  .no-results { text-align: center; color: #666; padding: 2rem; }
</style>
</head>
<body>
<h1>Contract Documentation</h1>
<p class="subtitle">Covers ${invariants.length} invariants. Generated by Stele.</p>

<div class="filters">
<input type="text" id="search" placeholder="Search invariants…" oninput="applyFilters()">
<select id="severityFilter" onchange="applyFilters()">
<option value="">All Severities</option>
${severities.map((s) => `<option value="${escapeHtml(s)}">${escapeHtml(s)}</option>`).join("\n")}
</select>
<select id="categoryFilter" onchange="applyFilters()">
<option value="">All Categories</option>
${categories.map((c) => `<option value="${escapeHtml(c)}">${escapeHtml(c)}</option>`).join("\n")}
</select>
</div>

<table>
<thead><tr><th>ID</th><th>Severity</th><th>Category</th><th>Description</th></tr></thead>
<tbody>
${rows}
</tbody>
</table>
<div id="noResults" class="no-results" style="display:none">No matching invariants.</div>

<div class="details">
${detailSections}
</div>

<script>
function applyFilters() {
  const query = document.getElementById('search').value.toLowerCase();
  const sev = document.getElementById('severityFilter').value;
  const cat = document.getElementById('categoryFilter').value;
  const rows = document.querySelectorAll('.inv-row');
  const details = document.querySelectorAll('.detail');
  let count = 0;

  rows.forEach((row) => {
    const matchSearch = !query || row.textContent.toLowerCase().includes(query);
    const matchSev = !sev || row.dataset.severity === sev;
    const matchCat = !cat || row.dataset.category === cat;
    const visible = matchSearch && matchSev && matchCat;
    row.classList.toggle('hidden', !visible);
    if (visible) count++;
  });

  details.forEach((d) => {
    const matchSearch = !query || d.textContent.toLowerCase().includes(query);
    const matchSev = !sev || d.dataset.severity === sev;
    const matchCat = !cat || d.dataset.category === cat;
    d.classList.toggle('hidden', !(matchSearch && matchSev && matchCat));
  });

  document.getElementById('noResults').style.display = count === 0 ? 'block' : 'none';
}
</script>
</body>
</html>`;
}

function uniqueString(arr: string[]): string[] {
  return [...new Set(arr)];
}
