import { mkdir, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { loadContract, type AstNode, type Contract } from "@stele/core";
import { loadConfig } from "../config/loadConfig.js";

export type DocOptions = {
  format?: "markdown" | "html";
  output?: string;
};

export async function runDoc(projectDir: string, options: DocOptions): Promise<void> {
  const config = await loadConfig(projectDir);
  const contract = await loadContract(resolve(projectDir, config.entry));

  let content: string;

  if (options.format === "html") {
    content = generateHtml(contract);
  } else {
    content = generateMarkdown(contract);
  }

  const outputDir = options.output ?? resolve(projectDir, "docs", "contract");
  const filename = options.format === "html" ? "index.html" : "contract.md";
  const outputPath = resolve(outputDir, filename);

  await mkdir(dirname(outputPath), { recursive: true });
  await writeFile(outputPath, content, "utf8");

  process.stdout.write(`[stele] Contract documentation written to ${filename}.\n`);
}

function formatNode(node: AstNode): string {
  switch (node.kind) {
    case "identifier":
      return node.value;
    case "keyword":
      return `:${node.value}`;
    case "string":
      return node.value;
    case "number":
      return node.raw;
    case "list":
      return `(${node.head} ${node.items.map(formatNode).join(" ")})`;
  }
}

function generateMarkdown(contract: Contract): string {
  const lines: string[] = [];
  lines.push("# Contract Documentation");
  lines.push("");
  lines.push(`Generated by Stele. Covers ${contract.invariants.length} invariants.`);
  lines.push("");

  for (const inv of contract.invariants) {
    lines.push(`## ${inv.id}`);
    lines.push("");
    lines.push("| Field | Value |");
    lines.push("|-------|-------|");
    lines.push(`| Severity | ${inv.severity} |`);
    lines.push(`| Description | ${inv.description} |`);
    if (inv.category) {
      lines.push(`| Category | ${formatNode(inv.category.valueNode)} |`);
    }
    if (inv.rationale) {
      lines.push(`| Rationale | ${formatNode(inv.rationale.valueNode)} |`);
    }
    if (inv.since) {
      lines.push(`| Since | ${formatNode(inv.since.valueNode)} |`);
    }
    lines.push("");
  }

  return lines.join("\n");
}

function escapeHtml(s: string): string {
  return s.replaceAll("&", "&amp;").replaceAll("<", "&lt;").replaceAll(">", "&gt;").replaceAll('"', "&quot;");
}

function generateHtml(contract: Contract): string {
  const rows = contract.invariants
    .map(
      (inv) =>
        `<tr><td>${escapeHtml(inv.id)}</td><td>${escapeHtml(inv.severity)}</td><td>${escapeHtml(inv.description ?? "")}</td></tr>`,
    )
    .join("\n");

  return `<!DOCTYPE html>
<html>
<head><title>Contract Documentation</title></head>
<body>
<h1>Contract Documentation</h1>
<p>Covers ${contract.invariants.length} invariants.</p>
<table>
<tr><th>ID</th><th>Severity</th><th>Description</th></tr>
${rows}
</table>
</body>
</html>`;
}
