// _stele_runtime.ts (auto-generated by @stele/backend-typescript; do not edit)

export class SteleRuntimeError extends Error {
  constructor(message: string) {
    super(message);
    this.name = "SteleRuntimeError";
  }
}

/**
 * Quantifier failure witness payload (EP07 §3.1).
 *
 * Schema mirrors `FailureWitness` in `@stele/core/src/report/types.ts`. The
 * runtime keeps a local copy so the generated `_stele_runtime.ts` is
 * self-contained and does not depend on `@stele/core` at user-runtime.
 */
export type FailureWitness = {
  operator: "forall" | "exists" | "where" | "none";
  collection_size: number;
  failed_at_index?: number;
  failed_item?: unknown;
  predicate_source?: string;
  truncated: boolean;
};

/**
 * Assertion failure with attached `FailureWitness`.
 *
 * Thrown by `steleForall` / `steleExists` / `steleWhere` / `steleNone` when
 * the quantifier predicate fails at runtime. Test framework setup files
 * (e.g. `_stele_setup.ts`) catch this error and forward `witness` into the
 * violation report (`ViolationCause.failure_witness`).
 */
export class SteleAssertionFailed extends Error {
  readonly witness: FailureWitness;
  constructor(message: string, witness: FailureWitness) {
    super(message);
    this.name = "SteleAssertionFailed";
    this.witness = witness;
  }
}

export type CheckerResult = {
  passed: boolean;
  message?: string | null;
  details?: unknown;
};

export type CheckerFn = (ctx: SteleContext, args: Record<string, unknown>) => boolean | CheckerResult;

export type ScenarioStep = {
  kind: "step" | "capture-state";
  id?: string;
  capture?: string;
  call: {
    target: string;
    body?: unknown;
  };
};

export type ScenarioDefinition = {
  id?: string;
  executor?: string;
  sandbox?: string;
  steps: ScenarioStep[];
};

export type ScenarioSandbox = {
  enter?(): void | Promise<void>;
  exit?(): void | Promise<void>;
};

export interface SteleContext {
  [key: string]: unknown;
  _stele_checkers?: Record<string, CheckerFn>;
  "state-before"?: SteleContext;
  "state-after"?: SteleContext;
}

/**
 * Resolve a sequence of path segments against an object.
 *
 * Lookup order at each segment:
 *   1. Direct own-property hit (record[seg]).
 *   2. kebab-case to camelCase fallback (e.g. "balance-history" -> "balanceHistory").
 *   3. Otherwise: throw SteleRuntimeError.
 *
 * Mirrors the contract path semantics defined by the Python backend; see
 * docs/spec/cdl.md "Path semantics".
 */
export function steleGetPath(obj: unknown, segments: readonly string[]): unknown {
  let current: unknown = obj;
  for (const seg of segments) {
    if (current === null || current === undefined) {
      throw new SteleRuntimeError(`Path not found: segment "${seg}" on null/undefined`);
    }
    if (Array.isArray(current)) {
      throw new SteleRuntimeError(
        `Path navigation hit array at "${seg}"; arrays must be navigated via collection operators`,
      );
    }
    if (typeof current !== "object") {
      throw new SteleRuntimeError(`Path navigation hit primitive at "${seg}"`);
    }
    const record = current as Record<string, unknown>;
    if (Object.prototype.hasOwnProperty.call(record, seg)) {
      current = record[seg];
      continue;
    }
    const camel = seg.replace(/-([a-z])/g, (_match, ch: string) => ch.toUpperCase());
    if (camel !== seg && Object.prototype.hasOwnProperty.call(record, camel)) {
      current = record[camel];
      continue;
    }
    throw new SteleRuntimeError(`Path not found: "${seg}" missing on object`);
  }
  return current;
}

/**
 * Deep-equality comparison with numeric tolerance.
 *
 * - Identical references compare equal.
 * - Two numbers compare equal when |a - b| <= 1e-9 OR (NaN, NaN).
 * - Arrays compare element-wise.
 * - Plain objects compare by sorted-key set then per-key.
 * - All other types fall back to strict equality.
 */
export function steleEq(a: unknown, b: unknown): boolean {
  if (a === b) {
    return true;
  }
  if (typeof a === "number" && typeof b === "number") {
    if (Number.isNaN(a) && Number.isNaN(b)) {
      return true;
    }
    return Math.abs(a - b) <= 1e-9;
  }
  if (a === null || b === null || a === undefined || b === undefined) {
    return false;
  }
  if (Array.isArray(a) && Array.isArray(b)) {
    if (a.length !== b.length) {
      return false;
    }
    for (let i = 0; i < a.length; i += 1) {
      if (!steleEq(a[i], b[i])) {
        return false;
      }
    }
    return true;
  }
  if (typeof a === "object" && typeof b === "object" && !Array.isArray(a) && !Array.isArray(b)) {
    const aRec = a as Record<string, unknown>;
    const bRec = b as Record<string, unknown>;
    const aKeys = Object.keys(aRec).sort();
    const bKeys = Object.keys(bRec).sort();
    if (aKeys.length !== bKeys.length) {
      return false;
    }
    for (let i = 0; i < aKeys.length; i += 1) {
      if (aKeys[i] !== bKeys[i]) {
        return false;
      }
    }
    for (const key of aKeys) {
      if (!steleEq(aRec[key], bRec[key])) {
        return false;
      }
    }
    return true;
  }
  return false;
}

export function steleNeq(a: unknown, b: unknown): boolean {
  return !steleEq(a, b);
}

function assertNumeric(label: string, value: unknown): number {
  if (typeof value !== "number" || Number.isNaN(value)) {
    throw new SteleRuntimeError(`${label}: expected number, got ${typeof value}`);
  }
  return value;
}

export function steleGt(a: unknown, b: unknown): boolean {
  return assertNumeric("gt", a) > assertNumeric("gt", b);
}

export function steleGte(a: unknown, b: unknown): boolean {
  return assertNumeric("gte", a) >= assertNumeric("gte", b);
}

export function steleLt(a: unknown, b: unknown): boolean {
  return assertNumeric("lt", a) < assertNumeric("lt", b);
}

export function steleLte(a: unknown, b: unknown): boolean {
  return assertNumeric("lte", a) <= assertNumeric("lte", b);
}

/** Absolute value with numeric type guard (mirrors Python `abs`). */
export function steleAbs(value: unknown): number {
  return Math.abs(assertNumeric("abs", value));
}

/**
 * Sum two or more values with numeric coercion. Mirrors Python's chained `+`.
 * Used by the translator instead of inline `+` so generated code typechecks
 * cleanly under `tsc --strict` even when operands originate from
 * `steleGetPath` (which returns `unknown`).
 */
export function steleAdd(...operands: unknown[]): number {
  if (operands.length < 2) {
    throw new SteleRuntimeError(`add: expected at least two operands, got ${operands.length}`);
  }
  let total = 0;
  for (let i = 0; i < operands.length; i += 1) {
    total += assertNumeric("add", operands[i]);
  }
  return total;
}

/** Multiply two or more values with numeric coercion. Mirrors Python's chained `*`. */
export function steleMul(...operands: unknown[]): number {
  if (operands.length < 2) {
    throw new SteleRuntimeError(`mul: expected at least two operands, got ${operands.length}`);
  }
  let result = 1;
  for (let i = 0; i < operands.length; i += 1) {
    result *= assertNumeric("mul", operands[i]);
  }
  return result;
}

/** Subtract right from left with numeric coercion. Mirrors Python's binary `-`. */
export function steleSub(left: unknown, right: unknown): number {
  return assertNumeric("sub", left) - assertNumeric("sub", right);
}

/** Divide left by right with numeric coercion. Mirrors Python's binary `/`. */
export function steleDiv(left: unknown, right: unknown): number {
  return assertNumeric("div", left) / assertNumeric("div", right);
}

/** Negate a numeric value. Mirrors Python's unary `-`. */
export function steleNeg(value: unknown): number {
  return -assertNumeric("neg", value);
}

function assertCollection(label: string, value: unknown): unknown[] {
  if (!Array.isArray(value)) {
    throw new SteleRuntimeError(`${label}: expected array collection, got ${describeType(value)}`);
  }
  return value;
}

function describeType(value: unknown): string {
  if (value === null) {
    return "null";
  }
  if (Array.isArray(value)) {
    return "array";
  }
  return typeof value;
}

/**
 * Project items in a collection through a path (or identity when empty), then
 * return the projected values. Mirrors the Python pattern
 * `stele_get_path(item, parts) for item in items`.
 */
function projectCollection(label: string, items: readonly unknown[], parts: readonly string[]): unknown[] {
  if (parts.length === 0) {
    return [...items];
  }
  return items.map((item, index) => {
    try {
      return steleGetPath(item, parts);
    } catch (error) {
      if (error instanceof SteleRuntimeError) {
        throw new SteleRuntimeError(`${label}: projection failed at index ${index}: ${error.message}`);
      }
      throw error;
    }
  });
}

/**
 * Sum a collection of numbers (or path-projected numbers).
 * Mirrors Python `stele_sum` (`sum(items)` or `sum(stele_get_path(item, parts) for item in items)`).
 */
export function steleSum(items: unknown, parts: readonly string[] = []): number {
  const collection = assertCollection("sum", items);
  const projected = projectCollection("sum", collection, parts);
  let total = 0;
  for (let i = 0; i < projected.length; i += 1) {
    const value = projected[i];
    if (typeof value !== "number" || Number.isNaN(value)) {
      throw new SteleRuntimeError(`sum: expected number at index ${i}, got ${describeType(value)}`);
    }
    total += value;
  }
  return total;
}

/** Count items in a collection. Mirrors Python `len(items)`. */
export function steleCount(items: unknown): number {
  return assertCollection("count", items).length;
}

/**
 * Average a collection (or path-projected numbers).
 * Mirrors Python's `len and (sum/len) or 0` shortcut: empty collection -> 0.
 */
export function steleAvg(items: unknown, parts: readonly string[] = []): number {
  const collection = assertCollection("avg", items);
  if (collection.length === 0) {
    return 0;
  }
  return steleSum(collection, parts) / collection.length;
}

/**
 * Minimum of a numeric collection (or path-projected numbers).
 * Throws on empty collection (mirrors Python `min(...)` raising ValueError).
 */
export function steleMin(items: unknown, parts: readonly string[] = []): number {
  const collection = assertCollection("min", items);
  if (collection.length === 0) {
    throw new SteleRuntimeError("min: cannot compute min of an empty collection");
  }
  const projected = projectCollection("min", collection, parts);
  let result: number | undefined;
  for (let i = 0; i < projected.length; i += 1) {
    const value = projected[i];
    if (typeof value !== "number" || Number.isNaN(value)) {
      throw new SteleRuntimeError(`min: expected number at index ${i}, got ${describeType(value)}`);
    }
    if (result === undefined || value < result) {
      result = value;
    }
  }
  return result as number;
}

/**
 * Maximum of a numeric collection (or path-projected numbers).
 * Throws on empty collection (mirrors Python `max(...)` raising ValueError).
 */
export function steleMax(items: unknown, parts: readonly string[] = []): number {
  const collection = assertCollection("max", items);
  if (collection.length === 0) {
    throw new SteleRuntimeError("max: cannot compute max of an empty collection");
  }
  const projected = projectCollection("max", collection, parts);
  let result: number | undefined;
  for (let i = 0; i < projected.length; i += 1) {
    const value = projected[i];
    if (typeof value !== "number" || Number.isNaN(value)) {
      throw new SteleRuntimeError(`max: expected number at index ${i}, got ${describeType(value)}`);
    }
    if (result === undefined || value > result) {
      result = value;
    }
  }
  return result as number;
}

/**
 * Return a deduplicated copy of a collection (preserving first-seen order).
 * Mirrors Python's `list(dict.fromkeys(items))`.
 */
export function steleDistinct(items: unknown, parts: readonly string[] = []): unknown[] {
  const collection = assertCollection("distinct", items);
  const projected = projectCollection("distinct", collection, parts);
  const seen = new Set<string>();
  const result: unknown[] = [];
  for (const value of projected) {
    const key = canonicalKey(value);
    if (!seen.has(key)) {
      seen.add(key);
      result.push(value);
    }
  }
  return result;
}

/**
 * Return true when every value in the collection is unique (after optional
 * projection). Mirrors Python `len(set(seq)) == len(seq)`.
 */
export function steleUnique(items: unknown, parts: readonly string[] = []): boolean {
  const collection = assertCollection("unique", items);
  const projected = projectCollection("unique", collection, parts);
  const seen = new Set<string>();
  for (const value of projected) {
    const key = canonicalKey(value);
    if (seen.has(key)) {
      return false;
    }
    seen.add(key);
  }
  return true;
}

/** Stable canonical key used by distinct/unique to compare arbitrary values. */
function canonicalKey(value: unknown): string {
  if (value === null) {
    return "n:null";
  }
  if (value === undefined) {
    return "n:undefined";
  }
  if (typeof value === "string") {
    return `s:${value}`;
  }
  if (typeof value === "number") {
    return `#:${value}`;
  }
  if (typeof value === "boolean") {
    return `b:${value}`;
  }
  return `j:${stableStringify(value)}`;
}

/** Deterministic JSON serialization (sorted keys) for use in canonical keys. */
function stableStringify(value: unknown): string {
  if (value === null || typeof value !== "object") {
    return JSON.stringify(value);
  }
  if (Array.isArray(value)) {
    return `[${value.map((item) => stableStringify(item)).join(",")}]`;
  }
  const record = value as Record<string, unknown>;
  const keys = Object.keys(record).sort();
  return `{${keys.map((key) => `${JSON.stringify(key)}:${stableStringify(record[key])}`).join(",")}}`;
}

/**
 * Length predicate. Mirrors Python `len(items) == expected`. Length is read
 * from arrays, strings, and plain objects (using `Object.keys`).
 */
export function steleHasLength(items: unknown, expected: unknown): boolean {
  if (typeof expected !== "number" || Number.isNaN(expected)) {
    throw new SteleRuntimeError(`has-length: expected length must be a number, got ${describeType(expected)}`);
  }
  return polymorphicLength("has-length", items) === expected;
}

/**
 * Empty predicate. Mirrors Python `len(items) == 0`. Works on arrays, strings,
 * and plain objects (using `Object.keys`).
 */
export function steleIsEmpty(items: unknown): boolean {
  return polymorphicLength("is-empty", items) === 0;
}

/**
 * Internal length helper used by has-length / is-empty. Distinct from the
 * public `steleLength` operator (EP04) which only accepts collections; this
 * variant accepts arrays, strings, and plain objects to preserve Phase B
 * has-length / is-empty semantics on multi-shape inputs.
 */
function polymorphicLength(label: string, value: unknown): number {
  if (Array.isArray(value)) {
    return value.length;
  }
  if (typeof value === "string") {
    return value.length;
  }
  if (value !== null && typeof value === "object") {
    return Object.keys(value as Record<string, unknown>).length;
  }
  throw new SteleRuntimeError(`${label}: cannot compute length of ${describeType(value)}`);
}

/**
 * Container membership. Mirrors Python's `value in container` for sequences
 * and strings. Object containers test against own-key set.
 */
export function steleExistsIn(value: unknown, container: unknown): boolean {
  if (Array.isArray(container)) {
    for (const candidate of container) {
      if (steleEq(candidate, value)) {
        return true;
      }
    }
    return false;
  }
  if (typeof container === "string") {
    if (typeof value !== "string") {
      throw new SteleRuntimeError(
        `exists-in: cannot test ${describeType(value)} membership in a string container`,
      );
    }
    return container.includes(value);
  }
  if (container !== null && typeof container === "object") {
    if (typeof value !== "string") {
      return false;
    }
    return Object.prototype.hasOwnProperty.call(container, value);
  }
  throw new SteleRuntimeError(
    `exists-in: container must be array, string, or object; got ${describeType(container)}`,
  );
}

/** Substring containment. Mirrors Python's `needle in haystack` for strings. */
export function steleContains(haystack: unknown, needle: unknown): boolean {
  if (typeof haystack !== "string") {
    throw new SteleRuntimeError(`contains: haystack must be a string, got ${describeType(haystack)}`);
  }
  if (typeof needle !== "string") {
    throw new SteleRuntimeError(`contains: needle must be a string, got ${describeType(needle)}`);
  }
  return haystack.includes(needle);
}

/** Prefix predicate. Mirrors Python's `str.startswith`. */
export function steleStartsWith(value: unknown, prefix: unknown): boolean {
  if (typeof value !== "string") {
    throw new SteleRuntimeError(`starts-with: value must be a string, got ${describeType(value)}`);
  }
  if (typeof prefix !== "string") {
    throw new SteleRuntimeError(`starts-with: prefix must be a string, got ${describeType(prefix)}`);
  }
  return value.startsWith(prefix);
}

/** Suffix predicate. Mirrors Python's `str.endswith`. */
export function steleEndsWith(value: unknown, suffix: unknown): boolean {
  if (typeof value !== "string") {
    throw new SteleRuntimeError(`ends-with: value must be a string, got ${describeType(value)}`);
  }
  if (typeof suffix !== "string") {
    throw new SteleRuntimeError(`ends-with: suffix must be a string, got ${describeType(suffix)}`);
  }
  return value.endsWith(suffix);
}

/**
 * Regex search predicate. Mirrors Python `re.search(pattern, value) is not None`
 * (substring match; not anchored). Lookbehind is rejected to match the spec
 * (docs/design/phase-1/01-typescript-backend.md §7).
 */
/**
 * Detect potentially catastrophic backtracking patterns in a regex string.
 *
 * Checks for nested quantifiers such as `(a+)+`, `(a|b)*`, `(.*?)*` etc.
 * This is a heuristic — it may produce false negatives (miss some patterns)
 * but aims to avoid false positives on benign patterns.
 */
function hasRedoSPattern(pattern: string): boolean {
  let depth = 0;
  let i = 0;
  while (i < pattern.length) {
    const ch = pattern[i];
    if (ch === "\\") {
      i += 2;
      continue;
    }
    if (ch === "(") {
      depth += 1;
      i += 1;
      continue;
    }
    if (ch === ")") {
      depth = Math.max(0, depth - 1);
      // Check for quantifier after the closing paren
      if (i + 1 < pattern.length && (pattern[i + 1] === "+" || pattern[i + 1] === "*")) {
        // This group has a quantifier. If we're inside another quantified
        // group (depth > 0), or the group itself contains a quantifier,
        // it's a potential ReDoS pattern.
        if (depth > 0) {
          return true;
        }
      }
      i += 1;
      continue;
    }
    // Check for quantifier on a literal/char-class
    if ((ch === "+" || ch === "*") && i > 0) {
      const prev = pattern[i - 1];
      // Quantifier follows a character class or escaped char — if nested
      // inside a group (depth > 0), that group may also be quantified.
      if (depth > 0 && (prev === "]" || prev === "\\")) {
        return true;
      }
    }
    i += 1;
  }
  return false;
}

export function steleMatches(value: unknown, pattern: unknown): boolean {
  if (typeof value !== "string") {
    throw new SteleRuntimeError(`matches: value must be a string, got ${describeType(value)}`);
  }
  if (typeof pattern !== "string") {
    throw new SteleRuntimeError(`matches: pattern must be a string, got ${describeType(pattern)}`);
  }
  if (/\(\?<[!=]/.test(pattern)) {
    throw new SteleRuntimeError(`matches: lookbehind is not supported (pattern: ${pattern})`);
  }
  if (hasRedoSPattern(pattern)) {
    throw new SteleRuntimeError(`matches: pattern may cause catastrophic backtracking (ReDoS). Use anchored or non-nested quantifiers instead.`);
  }
  let regex: RegExp;
  try {
    regex = new RegExp(pattern);
  } catch (error) {
    const detail = error instanceof Error ? error.message : String(error);
    throw new SteleRuntimeError(`matches: invalid regex pattern ${JSON.stringify(pattern)}: ${detail}`);
  }
  return regex.test(value);
}

/** True when value is neither null nor undefined. Mirrors Python `x is not None`. */
export function steleNotNull(value: unknown): boolean {
  return value !== null && value !== undefined;
}

/** Inclusive range predicate. Mirrors Python `low <= value <= high`. */
export function steleBetween(value: unknown, low: unknown, high: unknown): boolean {
  const v = assertNumeric("between", value);
  const lo = assertNumeric("between", low);
  const hi = assertNumeric("between", high);
  return lo <= v && v <= hi;
}

/** Tolerant equality. Mirrors Python `abs(a - b) <= tol`. */
export function steleApproxEq(a: unknown, b: unknown, tolerance: unknown): boolean {
  const left = assertNumeric("approx-eq", a);
  const right = assertNumeric("approx-eq", b);
  const tol = assertNumeric("approx-eq", tolerance);
  return Math.abs(left - right) <= tol;
}

// ---------------------------------------------------------------------------
// EP04 batch 1: collection / arithmetic / string / data access / FP helpers
// ---------------------------------------------------------------------------

/** Number of elements in a collection. Empty -> 0; non-collection -> SteleRuntimeError. */
export function steleLength(coll: unknown): number {
  return assertCollection("length", coll).length;
}

/** Variadic flat concatenation. Preserves duplicates and order. */
export function steleConcat(...collections: unknown[]): unknown[] {
  if (collections.length < 1) {
    throw new SteleRuntimeError("concat: expected at least one collection operand");
  }
  const out: unknown[] = [];
  for (let i = 0; i < collections.length; i += 1) {
    const items = assertCollection(`concat[${i}]`, collections[i]);
    for (const value of items) {
      out.push(value);
    }
  }
  return out;
}

type SortRank = readonly [primary: number, secondary: number, payload: unknown];

/**
 * Total ordering rank for sort-by / sort-by-desc.
 *
 * Rank tiers (ascending sort):
 *   0: NaN -> first
 *   1: numbers (or booleans cast to number) and strings -> middle
 *   2: null / undefined -> last
 *
 * Inside tier 1, numbers compare by `<` and strings compare by lexicographic
 * UTF-16 code unit order (matches Python's lexicographic byte order for ASCII;
 * for non-ASCII the byte/codepoint distinction matches because both backends
 * agree on the same `<` semantics on Unicode strings without locale rules).
 */
function steleSortRank(value: unknown): SortRank {
  if (value === null || value === undefined) {
    return [2, 0, 0];
  }
  if (typeof value === "number") {
    if (Number.isNaN(value)) {
      return [0, 0, 0];
    }
    return [1, 0, value];
  }
  if (typeof value === "boolean") {
    return [1, 0, value ? 1 : 0];
  }
  if (typeof value === "string") {
    return [1, 1, value];
  }
  return [1, 2, JSON.stringify(value)];
}

function compareSortRank(left: SortRank, right: SortRank): number {
  if (left[0] !== right[0]) return left[0] - right[0];
  if (left[1] !== right[1]) return left[1] - right[1];
  if (typeof left[2] === "number" && typeof right[2] === "number") {
    return left[2] === right[2] ? 0 : left[2] < right[2] ? -1 : 1;
  }
  if (typeof left[2] === "string" && typeof right[2] === "string") {
    return left[2] === right[2] ? 0 : left[2] < right[2] ? -1 : 1;
  }
  return 0;
}

function projectForSort(label: string, items: readonly unknown[], parts: readonly string[]): unknown[] {
  if (parts.length === 0) {
    return items.slice();
  }
  return items.map((item) => {
    try {
      return steleGetPath(item, parts);
    } catch (error) {
      if (error instanceof SteleRuntimeError) {
        // Treat missing-path values as null/undefined so they sort to the end.
        return null;
      }
      throw error;
    }
  });
  // The label is only used in error messages; we currently never throw from
  // here since steleGetPath errors are recovered to null for ordering.
  void label;
}

/** Stable ascending sort by a path projection. Mirrors Python stele_sort_by. */
export function steleSortBy(coll: unknown, parts: readonly string[]): unknown[] {
  const items = assertCollection("sort-by", coll);
  const projected = projectForSort("sort-by", items, parts);
  const indexed = items.map((item, index) => ({ index, rank: steleSortRank(projected[index]) }));
  indexed.sort((left, right) => compareSortRank(left.rank, right.rank) || left.index - right.index);
  return indexed.map((entry) => items[entry.index]);
}

/** Stable descending sort by a path projection. Mirrors Python stele_sort_by_desc. */
export function steleSortByDesc(coll: unknown, parts: readonly string[]): unknown[] {
  const items = assertCollection("sort-by-desc", coll);
  const projected = projectForSort("sort-by-desc", items, parts);
  const indexed = items.map((item, index) => ({ index, rank: steleSortRank(projected[index]) }));
  // Stable descending: invert tier ordering for tier 1 keys, leave NaN (0) and
  // null (2) on their respective ends inverted to "first/last" via custom map.
  indexed.sort((left, right) => {
    const leftInverted = invertRankForDesc(left.rank);
    const rightInverted = invertRankForDesc(right.rank);
    return compareSortRank(leftInverted, rightInverted) || left.index - right.index;
  });
  return indexed.map((entry) => items[entry.index]);
}

function invertRankForDesc(rank: SortRank): SortRank {
  // Tier 0 (NaN) and Tier 2 (null) keep their tier so NaN stays first and null
  // stays last in both ascending and descending sorts (mirrors Python).
  if (rank[0] === 0 || rank[0] === 2) {
    return rank;
  }
  if (rank[1] === 0 && typeof rank[2] === "number") {
    return [1, 0, -rank[2]];
  }
  if (rank[1] === 1 && typeof rank[2] === "string") {
    // Build a string whose lexicographic order is the reverse of the original.
    return [1, 1, invertStringForDesc(rank[2])];
  }
  return rank;
}

function invertStringForDesc(value: string): string {
  // Map each code unit u -> (0xFFFF - u) so '<' on the inverted string yields
  // the reverse of '<' on the original. Locale-independent and consistent with
  // the Python helper which inverts via per-codepoint negation.
  let out = "";
  for (let i = 0; i < value.length; i += 1) {
    out += String.fromCharCode(0xffff - value.charCodeAt(i));
  }
  return out;
}

/** Sign-of-divisor modulo (Python semantics). Divisor of zero -> SteleRuntimeError. */
export function steleMod(left: unknown, right: unknown): number {
  const a = assertNumeric("mod", left);
  const b = assertNumeric("mod", right);
  if (b === 0) {
    throw new SteleRuntimeError("mod: divisor cannot be zero");
  }
  // JS % is sign-of-dividend; wrap to match Python's sign-of-divisor.
  return ((a % b) + b) % b;
}

/** IEEE-754 double power. Negative base + non-integer exponent -> NaN. */
export function stelePow(base: unknown, exponent: unknown): number {
  const baseN = assertNumeric("pow", base);
  const expN = assertNumeric("pow", exponent);
  // Math.pow already returns NaN for negative base + non-integer exponent so
  // no extra branching is required for cross-backend parity.
  return Math.pow(baseN, expN);
}

/**
 * Numeric guard that allows NaN to flow through for operators that propagate
 * NaN by spec (round / ceil / floor). Like `assertNumeric` but accepts NaN.
 */
function assertNumericAllowNan(label: string, value: unknown): number {
  if (typeof value !== "number") {
    throw new SteleRuntimeError(`${label}: expected number, got ${describeType(value)}`);
  }
  return value;
}

/**
 * Banker's rounding (round half to even). Mirrors Python 3's built-in `round`.
 *
 * JS Math.round is half-away-from-zero, so we manually compute the nearest
 * value and break ties to even. NaN / Infinity propagate (no error).
 */
export function steleRound(value: unknown, digits: unknown = 0): number {
  const valueN = assertNumericAllowNan("round", value);
  const digitsN = assertNumericAllowNan("round", digits);
  if (!Number.isInteger(digitsN)) {
    throw new SteleRuntimeError("round: digits must be an integer-valued number");
  }
  if (Number.isNaN(valueN) || !Number.isFinite(valueN)) {
    return valueN;
  }
  const m = Math.pow(10, digitsN);
  const scaled = valueN * m;
  const floor = Math.floor(scaled);
  const diff = scaled - floor;
  let rounded: number;
  if (diff < 0.5) {
    rounded = floor;
  } else if (diff > 0.5) {
    rounded = floor + 1;
  } else {
    // Half-to-even tie break: keep floor when it's already even.
    rounded = floor % 2 === 0 ? floor : floor + 1;
  }
  return rounded / m;
}

/** Round toward positive infinity; NaN propagates (no error). */
export function steleCeil(value: unknown): number {
  const v = assertNumericAllowNan("ceil", value);
  if (Number.isNaN(v)) return Number.NaN;
  return Math.ceil(v);
}

/** Round toward negative infinity; NaN propagates (no error). */
export function steleFloor(value: unknown): number {
  const v = assertNumericAllowNan("floor", value);
  if (Number.isNaN(v)) return Number.NaN;
  return Math.floor(v);
}

function assertString(label: string, value: unknown): string {
  if (typeof value !== "string") {
    throw new SteleRuntimeError(`${label}: expected string, got ${describeType(value)}`);
  }
  return value;
}

/** Strip leading and trailing Unicode whitespace. Mirrors JS String.trim. */
export function steleTrim(value: unknown): string {
  return assertString("trim", value).trim();
}

/** Locale-independent Unicode lowercase. */
export function steleLower(value: unknown): string {
  return assertString("lower", value).toLowerCase();
}

/** Locale-independent Unicode uppercase. */
export function steleUpper(value: unknown): string {
  return assertString("upper", value).toUpperCase();
}

/** Split a string by a literal separator. Empty separator -> SteleRuntimeError. */
export function steleSplit(value: unknown, sep: unknown): string[] {
  const valueS = assertString("split", value);
  const sepS = assertString("split", sep);
  if (sepS === "") {
    throw new SteleRuntimeError("split: separator cannot be empty");
  }
  return valueS.split(sepS);
}

/** Join a collection of strings with a separator; mixed types -> SteleRuntimeError. */
export function steleJoin(coll: unknown, sep: unknown): string {
  const items = assertCollection("join", coll);
  const sepS = assertString("join", sep);
  for (let i = 0; i < items.length; i += 1) {
    if (typeof items[i] !== "string") {
      throw new SteleRuntimeError(
        `join: collection element at index ${i} is not a string (got ${describeType(items[i])})`,
      );
    }
  }
  return (items as string[]).join(sepS);
}

/**
 * Return one of: "number", "string", "boolean", "collection", "object", "null", "undefined".
 *
 * Cross-backend mapping (Python has no separate "undefined", so it always
 * returns "null" for None; TypeScript distinguishes null vs undefined here).
 */
export function steleTypeOf(value: unknown): string {
  if (value === null) return "null";
  if (value === undefined) return "undefined";
  const tag = typeof value;
  if (tag === "number") return "number";
  if (tag === "string") return "string";
  if (tag === "boolean") return "boolean";
  if (Array.isArray(value)) return "collection";
  return "object";
}

/**
 * Extract a value from a JSON string using a simplified JSONPath expression.
 * Supports root fields, nested dot paths, array index access [N], and wildcard [*].
 * Returns JSON-encoded string for multiple matches, plain string for single matches.
 */
export function steleJsonPath(data: unknown, pathExpr: unknown): string {
  const dataS = assertString("json-path", data);
  const pathS = assertString("json-path", pathExpr);
  let root: unknown;
  try {
    root = JSON.parse(dataS);
  } catch (error) {
    throw new SteleRuntimeError(`json-path: invalid JSON input: ${error}`);
  }
  const results = _steleEvalJsonPath(root, pathS);
  if (results.length === 1) {
    return String(results[0]);
  }
  return JSON.stringify(results);
}

function _steleEvalJsonPath(data: unknown, path: string): unknown[] {
  if (!path) return [data];
  const tokens = _steleTokenizePath(path);
  if (!tokens.length) return [data];
  const [kind, value] = tokens[0]!;
  const rest = _steleDetokenize(tokens.slice(1));
  if (kind === "field") {
    if (typeof data === "object" && data !== null && !Array.isArray(data) && value in data) {
      return _steleEvalJsonPath((data as Record<string, unknown>)[value], rest);
    }
    return [];
  }
  if (kind === "index") {
    if (Array.isArray(data) && Number.isInteger(value) && value >= 0 && value < data.length) {
      return _steleEvalJsonPath(data[value], rest);
    }
    return [];
  }
  if (kind === "wildcard") {
    if (Array.isArray(data)) {
      const all: unknown[] = [];
      for (const item of data) {
        all.push(..._steleEvalJsonPath(item, rest));
      }
      return all;
    }
    return [];
  }
  return [];
}

type _JsonPathToken = ["field", string] | ["index", number] | ["wildcard"];

function _steleTokenizePath(path: string): _JsonPathToken[] {
  const tokens: _JsonPathToken[] = [];
  let i = 0;
  while (i < path.length) {
    if (path[i] === ".") {
      i++;
      continue;
    }
    if (path[i] === "[") {
      const j = path.indexOf("]", i);
      if (j === -1) throw new SteleRuntimeError(`json-path: unclosed bracket in path`);
      const inner = path.substring(i + 1, j);
      if (inner === "*") {
        tokens.push(["wildcard"]);
      } else {
        const idx = Number.parseInt(inner, 10);
        if (!Number.isInteger(idx)) {
          throw new SteleRuntimeError(`json-path: invalid array index: ${inner}`);
        }
        tokens.push(["index", idx]);
      }
      i = j + 1;
      continue;
    }
    const start = i;
    while (i < path.length && path[i] !== "." && path[i] !== "[") i++;
    const name = path.substring(start, i);
    if (name) tokens.push(["field", name]);
  }
  return tokens;
}

function _steleDetokenize(tokens: _JsonPathToken[]): string {
  return tokens.map(([k, v]) => {
    if (k === "field") return `.${v}`;
    if (k === "index") return `[${v}]`;
    return "[*]";
  }).join("");
}

/**
 * Compare two numbers with exact decimal precision, avoiding floating point errors.
 * Converts both operands to string first, then uses decimal string comparison.
 */
export function steleDecimalEq(left: unknown, right: unknown): boolean {
  const l = assertNumeric("decimal-eq", left);
  const r = assertNumeric("decimal-eq", right);
  // Use string representation to avoid floating point comparison issues.
  // Both are already Numbers in JS, so convert to fixed-point string for exact comparison.
  const lStr = Number.isInteger(l) ? String(l) : l.toFixed(20).replace(/0+$/, "").replace(/\.$/, "");
  const rStr = Number.isInteger(r) ? String(r) : r.toFixed(20).replace(/0+$/, "").replace(/\.$/, "");
  return lStr === rStr;
}

/** Project items by path; missing-path elements skipped silently (per spec). */
export function steleMap(coll: unknown, parts: readonly string[]): unknown[] {
  const items = assertCollection("map", coll);
  if (parts.length === 0) {
    return items.slice();
  }
  const out: unknown[] = [];
  for (const item of items) {
    try {
      out.push(steleGetPath(item, parts));
    } catch (error) {
      if (error instanceof SteleRuntimeError) {
        continue;
      }
      throw error;
    }
  }
  return out;
}

/** First element of a collection. Empty -> SteleRuntimeError. */
export function steleFirst(coll: unknown): unknown {
  const items = assertCollection("first", coll);
  if (items.length === 0) {
    throw new SteleRuntimeError("first: cannot read first element of empty collection");
  }
  return items[0];
}

/** Last element of a collection. Empty -> SteleRuntimeError. */
export function steleLast(coll: unknown): unknown {
  const items = assertCollection("last", coll);
  if (items.length === 0) {
    throw new SteleRuntimeError("last: cannot read last element of empty collection");
  }
  return items[items.length - 1];
}

// ---------------------------------------------------------------------------
// Phase C: failure-witness serialization (EP07 §3.2)
// ---------------------------------------------------------------------------

const STELE_MAX_WITNESS_BYTES = 64 * 1024;
const STELE_MAX_PREDICATE_SOURCE_BYTES = 4 * 1024;
const STELE_MAX_FAILED_ITEM_BYTES = 8 * 1024;
const STELE_MAX_ARRAY_ITEMS = 100;

const STELE_DEFAULT_REDACTION_PATTERNS: readonly RegExp[] = [
  /password/i,
  /token/i,
  /secret/i,
  /api[_-]?key/i,
];

/**
 * Defensive serialization for failure-witness payloads. Mirrors Python
 * `_safe_serialize` and the canonical implementation in `@stele/core`'s
 * `report/types.ts`.
 *
 * - Walks the tree up to `maxDepth`; deeper subtrees become "<depth-limit>"
 *   and `truncated` is set.
 * - Arrays longer than 100 entries are sliced.
 * - Object keys matching `redactionPatterns` are replaced with "<redacted>"
 *   (default patterns: password, token, secret, api[_-]?key — case-insensitive).
 * - JSON length is capped at 64 KB; on overflow the payload becomes a
 *   `{ _truncated, _original_size }` stub.
 */
export function safeSerialize(
  value: unknown,
  maxDepth: number,
  redactionPatterns: readonly RegExp[] = STELE_DEFAULT_REDACTION_PATTERNS,
): { serialized: unknown; truncated: boolean } {
  let truncated = false;

  const visit = (node: unknown, depth: number): unknown => {
    if (depth > maxDepth) {
      truncated = true;
      return "<depth-limit>";
    }
    if (node === null || node === undefined) {
      return node;
    }
    if (typeof node !== "object") {
      return node;
    }
    if (Array.isArray(node)) {
      if (node.length > STELE_MAX_ARRAY_ITEMS) {
        truncated = true;
      }
      return node.slice(0, STELE_MAX_ARRAY_ITEMS).map((entry) => visit(entry, depth + 1));
    }
    const out: Record<string, unknown> = {};
    for (const [key, entry] of Object.entries(node as Record<string, unknown>)) {
      if (redactionPatterns.some((pattern) => pattern.test(key))) {
        out[key] = "<redacted>";
        continue;
      }
      out[key] = visit(entry, depth + 1);
    }
    return out;
  };

  let result = visit(value, 0);
  let serialized: string;
  try {
    serialized = JSON.stringify(result);
  } catch {
    truncated = true;
    return { serialized: { _truncated: true, _serialize_error: true }, truncated };
  }
  if (serialized !== undefined && serialized.length > STELE_MAX_WITNESS_BYTES) {
    truncated = true;
    result = { _truncated: true, _original_size: serialized.length };
  }
  return { serialized: result, truncated };
}

function buildWitness(
  operator: FailureWitness["operator"],
  collectionSize: number,
  failedIndex: number | undefined,
  failedItem: unknown,
  predicateSource: string,
): FailureWitness {
  let truncated = false;

  let predicate: string | undefined = predicateSource;
  if (predicate !== undefined && predicate.length > STELE_MAX_PREDICATE_SOURCE_BYTES) {
    predicate = `${predicate.slice(0, STELE_MAX_PREDICATE_SOURCE_BYTES)}...<truncated>`;
    truncated = true;
  }

  let item: unknown = undefined;
  if (failedItem !== undefined) {
    const serialized = safeSerialize(failedItem, 2);
    item = serialized.serialized;
    if (serialized.truncated) {
      truncated = true;
    }
    const itemBytes = JSON.stringify(item ?? null) ?? "";
    if (itemBytes.length > STELE_MAX_FAILED_ITEM_BYTES) {
      item = { _truncated: true, _original_size: itemBytes.length };
      truncated = true;
    }
  }

  const witness: FailureWitness = {
    operator,
    collection_size: collectionSize,
    truncated,
  };
  if (failedIndex !== undefined) {
    witness.failed_at_index = failedIndex;
  }
  if (item !== undefined) {
    witness.failed_item = item;
  }
  if (predicate !== undefined) {
    witness.predicate_source = predicate;
  }
  return witness;
}

// ---------------------------------------------------------------------------
// Phase C: quantifiers
// ---------------------------------------------------------------------------

/**
 * Universal quantifier with witness emission (EP07).
 *
 * Iterates `coll` and runs `pred` on each item. On the first false result
 * throws `SteleAssertionFailed` carrying a `FailureWitness` whose
 * `predicate_source` is the literal CDL source of the predicate body
 * (recovered by the translator). Mirrors Python `stele_forall`.
 */
export function steleForall(coll: unknown, pred: (item: unknown) => boolean, predicateSource: string): boolean {
  const items = assertCollection("forall", coll);
  for (let i = 0; i < items.length; i += 1) {
    const item = items[i];
    let result: boolean;
    try {
      result = pred(item);
    } catch (error) {
      if (error instanceof SteleAssertionFailed || error instanceof SteleRuntimeError) {
        throw error;
      }
      const detail = error instanceof Error ? error.message : String(error);
      throw new SteleRuntimeError(`forall: predicate threw at index ${i}: ${detail}`);
    }
    if (!result) {
      throw new SteleAssertionFailed(
        `forall failed at index ${i}`,
        buildWitness("forall", items.length, i, item, predicateSource),
      );
    }
  }
  return true;
}

/**
 * Existential quantifier with witness emission (EP07).
 *
 * Returns true on the first item where `pred` returns truthy. If no item
 * matches, throws `SteleAssertionFailed` whose witness omits `failed_at_index`
 * and `failed_item` (no single witness item; the failure is "no satisfying
 * element"). Mirrors Python `stele_exists`.
 */
export function steleExists(coll: unknown, pred: (item: unknown) => boolean, predicateSource: string): boolean {
  const items = assertCollection("exists", coll);
  for (let i = 0; i < items.length; i += 1) {
    let result: boolean;
    try {
      result = pred(items[i]);
    } catch (error) {
      if (error instanceof SteleAssertionFailed || error instanceof SteleRuntimeError) {
        throw error;
      }
      const detail = error instanceof Error ? error.message : String(error);
      throw new SteleRuntimeError(`exists: predicate threw at index ${i}: ${detail}`);
    }
    if (result) {
      return true;
    }
  }
  throw new SteleAssertionFailed(
    `exists failed: no element in collection of size ${items.length} satisfies predicate`,
    buildWitness("exists", items.length, undefined, undefined, predicateSource),
  );
}

/**
 * Filter quantifier with witness emission (EP07).
 *
 * Returns the subset of `coll` for which `pred` is true. Empty result
 * triggers `SteleAssertionFailed` (matches Python `stele_where` semantics:
 * "where" filters and asserts non-empty so the assertion expressing
 * "filtered set is non-empty" is meaningful). The witness records
 * `collection_size` and `predicate_source`; no specific failed item.
 */
export function steleWhere(coll: unknown, pred: (item: unknown) => boolean, predicateSource: string): unknown[] {
  const items = assertCollection("where", coll);
  const matched: unknown[] = [];
  for (let i = 0; i < items.length; i += 1) {
    let result: boolean;
    try {
      result = pred(items[i]);
    } catch (error) {
      if (error instanceof SteleAssertionFailed || error instanceof SteleRuntimeError) {
        throw error;
      }
      const detail = error instanceof Error ? error.message : String(error);
      throw new SteleRuntimeError(`where: predicate threw at index ${i}: ${detail}`);
    }
    if (result) {
      matched.push(items[i]);
    }
  }
  return matched;
}

/**
 * Negative quantifier with witness emission (EP07).
 *
 * Returns true when no item in `coll` satisfies `pred`. The first satisfying
 * item triggers `SteleAssertionFailed` with witness for "this element should
 * not have matched". Mirrors Python `stele_none`.
 */
export function steleNone(coll: unknown, pred: (item: unknown) => boolean, predicateSource: string): boolean {
  const items = assertCollection("none", coll);
  for (let i = 0; i < items.length; i += 1) {
    const item = items[i];
    let result: boolean;
    try {
      result = pred(item);
    } catch (error) {
      if (error instanceof SteleAssertionFailed || error instanceof SteleRuntimeError) {
        throw error;
      }
      const detail = error instanceof Error ? error.message : String(error);
      throw new SteleRuntimeError(`none: predicate threw at index ${i}: ${detail}`);
    }
    if (result) {
      throw new SteleAssertionFailed(
        `none failed at index ${i}: predicate matched an element that should not match`,
        buildWitness("none", items.length, i, item, predicateSource),
      );
    }
  }
  return true;
}

// ---------------------------------------------------------------------------
// Phase C: temporal helpers
// ---------------------------------------------------------------------------

/**
 * Read `state-before` from the context. Mirrors Python
 * `stele_context["state-before"]`. Throws when the key is missing so
 * generated tests fail loudly instead of silently returning `undefined`.
 */
export function steleStateBefore(ctx: SteleContext): SteleContext {
  const value = ctx["state-before"];
  if (value === undefined || value === null) {
    throw new SteleRuntimeError("state-before: missing 'state-before' on stele_context");
  }
  if (typeof value !== "object" || Array.isArray(value)) {
    throw new SteleRuntimeError(`state-before: 'state-before' must be an object, got ${describeType(value)}`);
  }
  return value as SteleContext;
}

/** Symmetric helper for `state-after`. */
export function steleStateAfter(ctx: SteleContext): SteleContext {
  const value = ctx["state-after"];
  if (value === undefined || value === null) {
    throw new SteleRuntimeError("state-after: missing 'state-after' on stele_context");
  }
  if (typeof value !== "object" || Array.isArray(value)) {
    throw new SteleRuntimeError(`state-after: 'state-after' must be an object, got ${describeType(value)}`);
  }
  return value as SteleContext;
}

const STELE_MISSING = Symbol("stele.missing");
type SteleMissing = typeof STELE_MISSING;

function steleReadOptionalPath(root: unknown, parts: readonly string[]): unknown | SteleMissing {
  try {
    return steleGetPath(root, parts);
  } catch (error) {
    if (error instanceof SteleRuntimeError) {
      return STELE_MISSING;
    }
    throw error;
  }
}

/**
 * Compare `state-before[path]` and `state-after[path]` for inequality.
 *
 * Returns true when the values differ (including "missing on one side, present
 * on the other"). Throws when either snapshot is absent from `ctx`. Mirrors
 * Python `stele_is_modified`.
 */
export function steleIsModified(ctx: SteleContext, parts: readonly string[]): boolean {
  const before = steleStateBefore(ctx);
  const after = steleStateAfter(ctx);
  const beforeValue = steleReadOptionalPath(before, parts);
  const afterValue = steleReadOptionalPath(after, parts);
  if (beforeValue === STELE_MISSING || afterValue === STELE_MISSING) {
    return beforeValue !== afterValue;
  }
  return !steleEq(beforeValue, afterValue);
}

/** Strict ordering: `left < right` (Python `before` operator). */
export function steleBefore(left: unknown, right: unknown): boolean {
  return compareTemporal("before", left, right) < 0;
}

/** Strict ordering: `left > right` (Python `after` operator). */
export function steleAfter(left: unknown, right: unknown): boolean {
  return compareTemporal("after", left, right) > 0;
}

/**
 * `within(event, duration)` — true when `(now - event) < duration` seconds.
 *
 * Mirrors Python's `(datetime.now() - event) < timedelta(seconds=duration)`.
 * `event` and the implied "now" must both be Date instances or numeric
 * milliseconds-since-epoch. `duration` is a number of seconds.
 */
export function steleWithin(event: unknown, durationSeconds: unknown): boolean {
  const eventMs = toEpochMillis("within", event);
  if (typeof durationSeconds !== "number" || Number.isNaN(durationSeconds)) {
    throw new SteleRuntimeError(`within: duration must be a number of seconds, got ${describeType(durationSeconds)}`);
  }
  const now = Date.now();
  return now - eventMs < durationSeconds * 1000;
}

function compareTemporal(label: string, left: unknown, right: unknown): number {
  const a = toEpochMillis(label, left);
  const b = toEpochMillis(label, right);
  return a < b ? -1 : a > b ? 1 : 0;
}

function toEpochMillis(label: string, value: unknown): number {
  if (typeof value === "number" && !Number.isNaN(value)) {
    return value;
  }
  if (value instanceof Date) {
    const ms = value.getTime();
    if (Number.isNaN(ms)) {
      throw new SteleRuntimeError(`${label}: Date instance is invalid`);
    }
    return ms;
  }
  if (typeof value === "string") {
    const parsed = Date.parse(value);
    if (!Number.isNaN(parsed)) {
      return parsed;
    }
  }
  throw new SteleRuntimeError(
    `${label}: expected number/Date/parseable string, got ${describeType(value)}`,
  );
}

// ---------------------------------------------------------------------------
// Phase C: scenario / checker runtime
// ---------------------------------------------------------------------------

/**
 * Module-prefix allowlist for user-application code accessed from
 * scenarios. Mirrors Python's `_STELE_ALLOWED_MODULES`.
 *
 * In the TypeScript backend, scenario step targets are user-provided
 * functions registered on the conftest's `steleContext`; there is no
 * `importlib`-style dynamic import. We keep the prefix list around so
 * `assertImportAllowed` can check user-provided module names if scenarios
 * later add a `(target "module:fn")` form, matching Python semantics.
 */
export const STELE_USER_ALLOWED_MODULES: readonly string[] = [
  "tests/contract_scenarios",
  "tests/contract",
  "app",
];

/**
 * Globals an emitted contract may reference (per EP01 §7).
 *
 * Generated test files are pure functions of `ctx`; they only require `Math`
 * and `JSON` from the standard library. User application modules are
 * imported by user-owned `conftest.ts`, NOT by the runtime, so we do not
 * load them dynamically.
 */
export const STELE_ALLOWED_IMPORTS: ReadonlySet<string> = new Set(["Math", "JSON"]);

/**
 * Modules forbidden from scenario step targets. Mirrors Python
 * `_STELE_BLOCKED_MODULES`. Future scenario forms that accept a string
 * target should call `assertImportAllowed` to enforce this.
 */
export const STELE_BLOCKED_IMPORTS: ReadonlySet<string> = new Set([
  "fs",
  "fs/promises",
  "child_process",
  "net",
  "http",
  "https",
  "os",
  "path",
  "process",
  "vm",
  "node:fs",
  "node:fs/promises",
  "node:child_process",
  "node:net",
  "node:http",
  "node:https",
  "node:os",
  "node:path",
  "node:process",
  "node:vm",
]);

export function assertImportAllowed(moduleName: string): void {
  if (STELE_BLOCKED_IMPORTS.has(moduleName)) {
    throw new SteleRuntimeError(`Module "${moduleName}" is blocked by Stele safety policy`);
  }
  if (STELE_ALLOWED_IMPORTS.has(moduleName)) {
    return;
  }
  if (STELE_USER_ALLOWED_MODULES.some((prefix) => moduleName === prefix || moduleName.startsWith(`${prefix}/`))) {
    return;
  }
  throw new SteleRuntimeError(`Module "${moduleName}" is not in Stele allowlist`);
}

/**
 * Shallow merge a sequence of contexts, last write wins. Mirrors Python
 * `stele_merge_contexts`. Used to overlay scenario captures on top of the
 * base `stele_context` for predicate evaluation.
 */
export function steleMergeContexts(...contexts: ReadonlyArray<SteleContext | undefined | null>): SteleContext {
  const merged: Record<string, unknown> = {};
  for (const ctx of contexts) {
    if (ctx === null || ctx === undefined) {
      continue;
    }
    if (typeof ctx !== "object" || Array.isArray(ctx)) {
      throw new SteleRuntimeError("steleMergeContexts: contexts must be plain object dictionaries");
    }
    for (const [key, value] of Object.entries(ctx)) {
      merged[key] = value;
    }
  }
  return merged as SteleContext;
}

/**
 * Resolve a checker by name and invoke it.
 *
 * Mirrors Python `stele_call_checker(name, ctx, kwargs)`: looks up
 * `ctx._stele_checkers[name]`, calls it with `(ctx, args)`, and normalizes
 * the result to `{ passed, message? }`. Boolean-returning checkers are
 * wrapped in `{ passed: <bool>, message: null }`.
 */
export function steleCallChecker(
  name: string,
  ctx: SteleContext,
  args: Record<string, unknown> = {},
): CheckerResult {
  const registry = ctx._stele_checkers;
  if (registry === undefined || registry === null) {
    throw new SteleRuntimeError(
      "Stele checker registry not found at stele_context._stele_checkers",
    );
  }
  const checker = registry[name];
  if (checker === undefined) {
    throw new SteleRuntimeError(`Stele checker not registered: ${name}`);
  }
  if (typeof checker !== "function") {
    throw new SteleRuntimeError(`Stele checker '${name}' is not callable`);
  }
  const result = checker(ctx, args);
  if (typeof result === "boolean") {
    return { passed: result, message: null };
  }
  if (result === null || typeof result !== "object") {
    throw new SteleRuntimeError(`Stele checker '${name}' returned a non-object/non-boolean result`);
  }
  if (!("passed" in result)) {
    throw new SteleRuntimeError(`Stele checker '${name}' returned an object without 'passed'`);
  }
  return result;
}

function isSandbox(value: unknown): value is ScenarioSandbox {
  return typeof value === "object" && value !== null && (
    typeof (value as ScenarioSandbox).enter === "function" ||
    typeof (value as ScenarioSandbox).exit === "function"
  );
}

function resolveScenarioValue(
  value: unknown,
  scenarioContext: Record<string, unknown>,
): unknown {
  if (Array.isArray(value)) {
    return value.map((entry) => resolveScenarioValue(entry, scenarioContext));
  }
  if (value === null || value === undefined || typeof value !== "object") {
    return value;
  }
  const record = value as Record<string, unknown>;
  if ("$ref" in record) {
    const refParts = record.$ref;
    if (!Array.isArray(refParts) || refParts.length === 0) {
      throw new SteleRuntimeError(`Scenario $ref must be a non-empty array, got ${JSON.stringify(refParts)}`);
    }
    const head = refParts[0];
    if (typeof head !== "string") {
      throw new SteleRuntimeError("Scenario $ref capture name must be a string");
    }
    if (!(head in scenarioContext)) {
      throw new SteleRuntimeError(`Scenario $ref capture not bound: ${head}`);
    }
    const base = scenarioContext[head];
    if (refParts.length === 1) {
      return base;
    }
    return steleGetPath(base, refParts.slice(1) as string[]);
  }
  if ("$gen" in record) {
    return generateScenarioValue(record.$gen);
  }
  const out: Record<string, unknown> = {};
  for (const [key, entry] of Object.entries(record)) {
    out[key] = resolveScenarioValue(entry, scenarioContext);
  }
  return out;
}

function generateScenarioValue(spec: unknown): string {
  if (spec === null || typeof spec !== "object") {
    throw new SteleRuntimeError(`Scenario $gen spec must be an object, got ${describeType(spec)}`);
  }
  const record = spec as Record<string, unknown>;
  if (record.kind === "unique-name") {
    const prefix = typeof record.prefix === "string" ? record.prefix : "value";
    // Crypto-quality randomness is not required for unique-name; it just needs
    // collision avoidance within a test run.
    const random = `${Date.now().toString(36)}-${Math.random().toString(36).slice(2, 14)}`;
    return `${prefix}-${random}`;
  }
  throw new SteleRuntimeError(`Unsupported Stele scenario generator: ${String(record.kind)}`);
}

/**
 * Run a scenario against the provided context.
 *
 * Each step's `call.target` must be a function lookup name registered on
 * `ctx._stele_scenario_targets[<target>]` (or accessible via the user's
 * conftest in some other consumer-defined way). The returned object is the
 * scenario context (capture map); merge it with the original ctx via
 * `steleMergeContexts` to produce the final assertion context.
 *
 * Sandbox handling: if `sandbox` exposes `enter`/`exit`, they are invoked
 * around the loop. Mirrors Python's `_stele_open_sandbox`.
 */
export function steleRunScenario(
  scenario: ScenarioDefinition,
  ctx: SteleContext,
  sandbox?: ScenarioSandbox | null,
): SteleContext {
  const scenarioContext: Record<string, unknown> = {};
  const targets = (ctx as Record<string, unknown>)._stele_scenario_targets as
    | Record<string, (body: unknown, ctx: SteleContext) => unknown>
    | undefined;

  const enterSandbox = isSandbox(sandbox) && typeof sandbox.enter === "function" ? sandbox.enter.bind(sandbox) : undefined;
  const exitSandbox = isSandbox(sandbox) && typeof sandbox.exit === "function" ? sandbox.exit.bind(sandbox) : undefined;

  if (enterSandbox !== undefined) {
    enterSandbox();
  }
  try {
    for (const step of scenario.steps) {
      const target = step.call?.target;
      if (typeof target !== "string" || target.length === 0) {
        throw new SteleRuntimeError("Scenario step is missing call.target");
      }
      if (targets === undefined) {
        throw new SteleRuntimeError(
          `Scenario target "${target}" not found: ctx._stele_scenario_targets is missing. ` +
            "Define it in your conftest to dispatch scenarios.",
        );
      }
      const fn = targets[target];
      if (typeof fn !== "function") {
        throw new SteleRuntimeError(`Scenario target "${target}" is not registered`);
      }
      const body = resolveScenarioValue(step.call?.body, scenarioContext);
      const merged = steleMergeContexts(ctx, scenarioContext as SteleContext);
      const result = fn(body, merged);
      if (step.kind === "step") {
        const captureName = step.capture;
        if (typeof captureName === "string" && captureName.length > 0) {
          scenarioContext[captureName] = result;
        }
        continue;
      }
      if (step.kind === "capture-state") {
        const captureName = step.capture;
        if (typeof captureName !== "string" || captureName.length === 0) {
          throw new SteleRuntimeError("capture-state step is missing 'capture' name");
        }
        scenarioContext[captureName] = result;
        continue;
      }
      throw new SteleRuntimeError(`Unsupported Stele scenario step kind: ${(step as ScenarioStep).kind}`);
    }
  } finally {
    if (exitSandbox !== undefined) {
      exitSandbox();
    }
  }

  return scenarioContext as SteleContext;
}
