// stele_runtime_test.go (auto-generated by @stele/backend-go; do not edit)
package contract_test

import (
	"encoding/json"
	"fmt"
	"math"
	"os"
	"path/filepath"
	"reflect"
	"regexp"
	"sort"
	"strconv"
	"strings"
	"sync"
	"testing"
)

// ---------------------------------------------------------------------------
// Error types
// ---------------------------------------------------------------------------

// SteleRuntimeError is raised by runtime helpers when input validation fails.
type SteleRuntimeError struct {
	Message string
}

func (e *SteleRuntimeError) Error() string { return e.Message }

// ---------------------------------------------------------------------------
// FailureWitness (EP07)
// ---------------------------------------------------------------------------

// FailureWitness records the context of a quantifier operator failure.
// Field names match the FailureWitness type in @stele/core/src/report/types.ts,
// using snake_case JSON tags for cross-backend byte equivalence.
type FailureWitness struct {
	Operator        string `json:"operator"`
	CollectionSize  int    `json:"collection_size"`
	FailedAtIndex   *int   `json:"failed_at_index,omitempty"`
	FailedItem      any    `json:"failed_item,omitempty"`
	PredicateSource string `json:"predicate_source,omitempty"`
	Truncated       bool   `json:"truncated"`
}

// SteleAssertionError is returned by quantifier helpers on failure.
type SteleAssertionError struct {
	Message  string
	Witness  FailureWitness
	TestName string
}

func (e *SteleAssertionError) Error() string { return e.Message }

// ---------------------------------------------------------------------------
// Context / Checker / Scenario types
// ---------------------------------------------------------------------------

// SteleContext holds the data and checkers available to contract tests.
type SteleContext struct {
	Data     map[string]any
	Checkers map[string]CheckerFunc
	Before   *SteleContext // state-before
	After    *SteleContext // state-after
}

// CheckerFunc is a user-registered checker invoked by generated tests.
type CheckerFunc func(args []any, ctx *SteleContext) CheckerResult

// CheckerResult is the result of a checker invocation.
type CheckerResult struct {
	Ok      bool
	Message string
	Details any
}

// NewContext creates a SteleContext with initialized maps.
func NewContext() *SteleContext {
	return &SteleContext{
		Data:     make(map[string]any),
		Checkers: make(map[string]CheckerFunc),
	}
}

// Get returns the value for a key in the context data.
func (c *SteleContext) Get(key string) any {
	return c.Data[key]
}

// RegisterChecker adds a checker function to the context.
func (c *SteleContext) RegisterChecker(name string, fn CheckerFunc) {
	c.Checkers[name] = fn
}

// ScenarioStep represents a single step in a scenario execution.
type ScenarioStep struct {
	Type     string                 `json:"type"`
	Path     string                 `json:"path"`
	Expected any                    `json:"expected"`
	Args     map[string]any         `json:"args"`
}

// ---------------------------------------------------------------------------
// Witness emission (file-based channel)
// ---------------------------------------------------------------------------

const (
	maxWitnessDepth      = 2
	maxArrayItems        = 100
	maxFailedItemBytes   = 8 * 1024
	maxPredicateSourceKB = 4 * 1024
)

var redactionPatterns = []string{"password", "token", "secret", "api_key", "apikey"}

var witnessMu sync.Mutex
var witnessSeq int

// emitWitness writes a witness JSON file to the STELE_WITNESS_DIR.
func emitWitness(t *testing.T, w *FailureWitness) {
	dir := os.Getenv("STELE_WITNESS_DIR")
	if dir == "" {
		return
	}
	safeName := strings.ReplaceAll(t.Name(), "/", "_")
	witnessMu.Lock()
	witnessSeq++
	seq := witnessSeq
	witnessMu.Unlock()
	filename := fmt.Sprintf("%s-%04d.json", safeName, seq)
	path := filepath.Join(dir, filename)
	data, _ := json.Marshal(map[string]any{
		"test_name": t.Name(),
		"witness":   w,
	})
	_ = os.WriteFile(path, data, 0644)
}

// flushWitnessChannel is called before exit. Currently a no-op since
// emitWitness uses synchronous os.WriteFile.
func flushWitnessChannel() {
	// no-op: os.WriteFile is synchronous.
}

// ---------------------------------------------------------------------------
// safeSerialize (EP07 §3.2)
// ---------------------------------------------------------------------------

// safeSerialize defensively serializes a failure item, limiting depth,
// array length, and byte size. Mirrors safeSerialize() in @stele/core.
func safeSerialize(value any, maxDepth int) string {
	result, _ := safeSerializeTree(value, maxDepth, 0)
	data, err := json.Marshal(result)
	if err != nil {
		return `{"_truncated":true,"_serialize_error":true}`
	}
	if len(data) > maxFailedItemBytes {
		return fmt.Sprintf(`{"_truncated":true,"_original_size":%d}`, len(data))
	}
	return string(data)
}

func safeSerializeTree(value any, maxDepth, depth int) (any, bool) {
	if depth > maxDepth {
		return "<depth-limit>", true
	}
	if value == nil {
		return nil, false
	}

	switch v := value.(type) {
	case []any:
		if len(v) > maxArrayItems {
			v = v[:maxArrayItems]
		}
		out := make([]any, len(v))
		truncated := false
		for i, item := range v {
			var t bool
			out[i], t = safeSerializeTree(item, maxDepth, depth+1)
			if t {
				truncated = true
			}
		}
		return out, truncated
	case map[string]any:
		out := make(map[string]any)
		truncated := false
		for key, item := range v {
			if shouldRedact(key) {
				out[key] = "<redacted>"
				continue
			}
			var t bool
			out[key], t = safeSerializeTree(item, maxDepth, depth+1)
			if t {
				truncated = true
			}
		}
		return out, truncated
	default:
		return v, false
	}
}

func shouldRedact(key string) bool {
	lower := strings.ToLower(key)
	for _, pat := range redactionPatterns {
		if strings.Contains(lower, pat) {
			return true
		}
	}
	return false
}

// ---------------------------------------------------------------------------
// steleNumeric type lifting
// ---------------------------------------------------------------------------

// steleNumeric lifts arbitrary numeric types to (int64, float64, isFloat).
// Returns an error for non-numeric types.
func steleNumeric(v any) (int64, float64, bool, error) {
	switch n := v.(type) {
	case int:
		return int64(n), float64(n), false, nil
	case int8:
		return int64(n), float64(n), false, nil
	case int16:
		return int64(n), float64(n), false, nil
	case int32:
		return int64(n), float64(n), false, nil
	case int64:
		return n, float64(n), false, nil
	case uint:
		return int64(n), float64(n), false, nil
	case uint8:
		return int64(n), float64(n), false, nil
	case uint16:
		return int64(n), float64(n), false, nil
	case uint32:
		return int64(n), float64(n), false, nil
	case uint64:
		if n > math.MaxInt64 {
			return 0, float64(n), true, nil
		}
		return int64(n), float64(n), false, nil
	case float32:
		return int64(n), float64(n), true, nil
	case float64:
		if n == math.Trunc(n) && !math.IsInf(n, 0) {
			return int64(n), n, false, nil
		}
		return 0, n, true, nil
	case json.Number:
		if i, err := n.Int64(); err == nil {
			return i, float64(i), false, nil
		}
		if f, err := n.Float64(); err == nil {
			return 0, f, true, nil
		}
		return 0, 0, false, fmt.Errorf("cannot parse number: %s", n)
	default:
		return 0, 0, false, fmt.Errorf("expected number, got %T", v)
	}
}

// steleTryNumeric attempts to parse an arbitrary value as float64.
// Handles string representations of numbers ("42", "3.14") that steleNumeric
// does not cover. Returns (float64, true) on success, (0, false) on failure.
func steleTryNumeric(v any) (float64, bool) {
	switch n := v.(type) {
	case string:
		if i, err := strconv.ParseInt(n, 10, 64); err == nil {
			return float64(i), true
		}
		if f, err := strconv.ParseFloat(n, 64); err == nil {
			return f, true
		}
		return 0, false
	case json.Number:
		if f, err := n.Float64(); err == nil {
			return f, true
		}
		return 0, false
	default:
		s := fmt.Sprint(v)
		if f, err := strconv.ParseFloat(s, 64); err == nil {
			return f, true
		}
		return 0, false
	}
}

// ---------------------------------------------------------------------------
// Comparison operators
// ---------------------------------------------------------------------------

// steleEq compares two values with numeric tolerance and fallback to reflect.DeepEqual.
func steleEq(a, b any) bool {
	ai, af, aIsFloat, aErr := steleNumeric(a)
	bi, bf, bIsFloat, bErr := steleNumeric(b)
	if aErr != nil || bErr != nil {
		aNum, aOk := steleTryNumeric(a)
		bNum, bOk := steleTryNumeric(b)
		if aOk && bOk {
			return math.Abs(aNum-bNum) < 1e-9
		}
		return reflect.DeepEqual(a, b)
	}
	if aIsFloat || bIsFloat {
		return math.Abs(af-bf) < 1e-9
	}
	return ai == bi
}

func steleNeq(a, b any) bool {
	return !steleEq(a, b)
}

func steleGt(a, b any) bool {
	return steleNumericCompare("gt", a, b) > 0
}

func steleGte(a, b any) bool {
	return steleNumericCompare("gt", a, b) >= 0
}

func steleLt(a, b any) bool {
	return steleNumericCompare("lt", a, b) < 0
}

func steleLte(a, b any) bool {
	return steleNumericCompare("lte", a, b) <= 0
}

func steleNumericCompare(op string, a, b any) int {
	ai, _, aF, aErr := steleNumeric(a)
	bi, _, bF, bErr := steleNumeric(b)
	if aErr != nil || bErr != nil {
		an, aOk := steleTryNumeric(a)
		bn, bOk := steleTryNumeric(b)
		if !aOk || !bOk {
			panic(fmt.Sprintf("cannot compare %T and %T in %s", a, b, op))
		}
		if math.Abs(an-bn) < 1e-9 {
			return 0
		}
		if an < bn {
			return -1
		}
		return 1
	}
	if aF || bF {
		af := toFloat(a, op)
		bf := toFloat(b, op)
		if math.Abs(af-bf) < 1e-9 {
			return 0
		}
		if af < bf {
			return -1
		}
		return 1
	}
	if ai < bi {
		return -1
	}
	if ai > bi {
		return 1
	}
	return 0
}

// ---------------------------------------------------------------------------
// Arithmetic operators
// ---------------------------------------------------------------------------

func steleAdd(operands ...any) float64 {
	if len(operands) < 2 {
		panic(fmt.Sprintf("add: expected at least 2 operands, got %d", len(operands)))
	}
	var total float64
	for _, op := range operands {
		total += toFloat(op, "add")
	}
	return total
}

func steleSub(a, b any) float64 {
	return toFloat(a, "sub") - toFloat(b, "sub")
}

func steleMul(operands ...any) float64 {
	if len(operands) < 2 {
		panic(fmt.Sprintf("mul: expected at least 2 operands, got %d", len(operands)))
	}
	result := float64(1)
	for _, op := range operands {
		result *= toFloat(op, "mul")
	}
	return result
}

func steleDiv(a, b any) float64 {
	divisor := toFloat(b, "div")
	if divisor == 0 {
		panic("div: division by zero")
	}
	return toFloat(a, "div") / divisor
}

func steleNeg(a any) float64 {
	return -toFloat(a, "neg")
}

func steleAbs(a any) float64 {
	return math.Abs(toFloat(a, "abs"))
}

func steleMod(a, b any) float64 {
	divisor := toFloat(b, "mod")
	if divisor == 0 {
		panic("mod: divisor cannot be zero")
	}
	// sign-of-divisor (Python semantics): ((a%b)+b)%b
	aVal := toFloat(a, "mod")
	return math.Mod(math.Mod(aVal, divisor)+divisor, divisor)
}

func stelePow(a, b any) float64 {
	return math.Pow(toFloat(a, "pow"), toFloat(b, "pow"))
}

func steleRound(a any, digits ...any) float64 {
	val := toFloat(a, "round")
	d := float64(0)
	if len(digits) > 0 {
		d = toFloat(digits[0], "round")
	}
	if !math.IsInf(d, 0) && d != math.Trunc(d) {
		panic("round: digits must be an integer-valued number")
	}
	if math.IsNaN(val) || math.IsInf(val, 0) {
		return val
	}
	m := math.Pow(10, d)
	scaled := val * m
	floor := math.Floor(scaled)
	diff := scaled - floor
	var rounded float64
	if diff < 0.5 {
		rounded = floor
	} else if diff > 0.5 {
		rounded = floor + 1
	} else {
		if math.Floor(floor/2)*2 == floor {
			rounded = floor
		} else {
			rounded = floor + 1
		}
	}
	return rounded / m
}

func steleCeil(a any) float64 {
	val := toFloat(a, "ceil")
	if math.IsNaN(val) {
		return math.NaN()
	}
	return math.Ceil(val)
}

func steleFloor(a any) float64 {
	val := toFloat(a, "floor")
	if math.IsNaN(val) {
		return math.NaN()
	}
	return math.Floor(val)
}

func toFloat(v any, op string) float64 {
	_, f, _, err := steleNumeric(v)
	if err != nil {
		f, ok := steleTryNumeric(v)
		if !ok {
			panic(fmt.Sprintf("%s: expected number, got %T", op, v))
		}
		return f
	}
	return f
}

// ---------------------------------------------------------------------------
// Aggregate operators
// ---------------------------------------------------------------------------

func steleSum(coll any, pathSegments ...string) float64 {
	items := asCollection(coll, "sum")
	projected := projectCollection(items, pathSegments)
	var total float64
	for i, v := range projected {
		total += toFloat(v, fmt.Sprintf("sum[%d]", i))
	}
	return total
}

func steleCount(coll any) int {
	items := asCollection(coll, "count")
	return len(items)
}

func steleAvg(coll any, pathSegments ...string) float64 {
	items := asCollection(coll, "avg")
	if len(items) == 0 {
		return 0
	}
	projected := projectCollection(items, pathSegments)
	var total float64
	for _, v := range projected {
		total += toFloat(v, "avg")
	}
	return total / float64(len(items))
}

func steleMin(coll any, pathSegments ...string) float64 {
	items := asCollection(coll, "min")
	if len(items) == 0 {
		panic("min: cannot compute min of an empty collection")
	}
	projected := projectCollection(items, pathSegments)
	result := toFloat(projected[0], "min")
	for i, v := range projected[1:] {
		val := toFloat(v, fmt.Sprintf("min[%d]", i+1))
		if val < result {
			result = val
		}
	}
	return result
}

func steleMax(coll any, pathSegments ...string) float64 {
	items := asCollection(coll, "max")
	if len(items) == 0 {
		panic("max: cannot compute max of an empty collection")
	}
	projected := projectCollection(items, pathSegments)
	result := toFloat(projected[0], "max")
	for i, v := range projected[1:] {
		val := toFloat(v, fmt.Sprintf("max[%d]", i+1))
		if val > result {
			result = val
		}
	}
	return result
}

func steleDistinct(coll any, pathSegments ...string) []any {
	items := asCollection(coll, "distinct")
	projected := projectCollection(items, pathSegments)
	seen := make(map[string]bool)
	result := []any{}
	for _, v := range projected {
		key := canonicalKey(v)
		if !seen[key] {
			seen[key] = true
			result = append(result, v)
		}
	}
	return result
}

func steleUnique(coll any, pathSegments ...string) bool {
	items := asCollection(coll, "unique")
	projected := projectCollection(items, pathSegments)
	seen := make(map[string]bool)
	for _, v := range projected {
		key := canonicalKey(v)
		if seen[key] {
			return false
		}
		seen[key] = true
	}
	return true
}

func steleHasLength(coll any, expected any) bool {
	exp, _, _, err := steleNumeric(expected)
	if err != nil {
		panic(fmt.Sprintf("has-length: expected length must be a number, got %T", expected))
	}
	return polymorphicLength(coll) == int(exp)
}

func steleIsEmpty(coll any) bool {
	return polymorphicLength(coll) == 0
}

func polymorphicLength(value any) int {
	switch v := value.(type) {
	case []any:
		return len(v)
	case string:
		return len(v)
	case map[string]any:
		return len(v)
	default:
		panic(fmt.Sprintf("cannot compute length of %T", value))
	}
}

func steleExistsIn(value any, container any) bool {
	switch c := container.(type) {
	case []any:
		for _, candidate := range c {
			if steleEq(candidate, value) {
				return true
			}
		}
		return false
	case string:
		v, ok := value.(string)
		if !ok {
			panic(fmt.Sprintf("exists-in: cannot test %T membership in a string container", value))
		}
		return strings.Contains(c, v)
	case map[string]any:
		v, ok := value.(string)
		if !ok {
			return false
		}
		_, ok = c[v]
		return ok
	default:
		panic(fmt.Sprintf("exists-in: container must be array, string, or object; got %T", container))
	}
}

// ---------------------------------------------------------------------------
// String operators
// ---------------------------------------------------------------------------

func steleContains(haystack, needle any) bool {
	h, ok := haystack.(string)
	if !ok {
		panic(fmt.Sprintf("contains: haystack must be a string, got %T", haystack))
	}
	n, ok := needle.(string)
	if !ok {
		panic(fmt.Sprintf("contains: needle must be a string, got %T", needle))
	}
	return strings.Contains(h, n)
}

func steleStartsWith(value, prefix any) bool {
	v, ok := value.(string)
	if !ok {
		panic(fmt.Sprintf("starts-with: value must be a string, got %T", value))
	}
	p, ok := prefix.(string)
	if !ok {
		panic(fmt.Sprintf("starts-with: prefix must be a string, got %T", prefix))
	}
	return strings.HasPrefix(v, p)
}

func steleEndsWith(value, suffix any) bool {
	v, ok := value.(string)
	if !ok {
		panic(fmt.Sprintf("ends-with: value must be a string, got %T", value))
	}
	s, ok := suffix.(string)
	if !ok {
		panic(fmt.Sprintf("ends-with: suffix must be a string, got %T", suffix))
	}
	return strings.HasSuffix(v, s)
}

func steleMatches(value, pattern any) bool {
	v, ok := value.(string)
	if !ok {
		panic(fmt.Sprintf("matches: value must be a string, got %T", value))
	}
	p, ok := pattern.(string)
	if !ok {
		panic(fmt.Sprintf("matches: pattern must be a string, got %T", pattern))
	}
	re, err := regexp.Compile(p)
	if err != nil {
		panic(fmt.Sprintf("matches: invalid regex %s: %v", pattern, err))
	}
	return re.MatchString(v)
}

func steleTrim(value any) string {
	v, ok := value.(string)
	if !ok {
		panic(fmt.Sprintf("trim: expected string, got %T", value))
	}
	return strings.TrimSpace(v)
}

func steleLower(value any) string {
	v, ok := value.(string)
	if !ok {
		panic(fmt.Sprintf("lower: expected string, got %T", value))
	}
	return strings.ToLower(v)
}

func steleUpper(value any) string {
	v, ok := value.(string)
	if !ok {
		panic(fmt.Sprintf("upper: expected string, got %T", value))
	}
	return strings.ToUpper(v)
}

func steleSplit(value, sep any) []string {
	v, ok := value.(string)
	if !ok {
		panic(fmt.Sprintf("split: expected string, got %T", value))
	}
	s, ok := sep.(string)
	if !ok {
		panic(fmt.Sprintf("split: separator must be a string, got %T", sep))
	}
	if s == "" {
		panic("split: separator cannot be empty")
	}
	return strings.Split(v, s)
}

func steleJoin(coll any, sep any) string {
	items := asCollection(coll, "join")
	s, ok := sep.(string)
	if !ok {
		panic(fmt.Sprintf("join: separator must be a string, got %T", sep))
	}
	strs := make([]string, len(items))
	for i, item := range items {
		str, ok := item.(string)
		if !ok {
			panic(fmt.Sprintf("join: collection element at index %d is not a string", i))
		}
		strs[i] = str
	}
	return strings.Join(strs, s)
}

// steleJsonPath extracts a value from a JSON string using a simplified JSONPath expression.
func steleJsonPath(data any, pathExpr any) string {
	dataS, ok := data.(string)
	if !ok {
		panic(fmt.Sprintf("json-path: data must be a string, got %T", data))
	}
	pathS, ok := pathExpr.(string)
	if !ok {
		panic(fmt.Sprintf("json-path: path must be a string, got %T", pathExpr))
	}
	var root any
	if err := json.Unmarshal([]byte(dataS), &root); err != nil {
		panic(fmt.Sprintf("json-path: invalid JSON input: %v", err))
	}
	results := _steleEvalJsonPath(root, pathS)
	if len(results) == 1 {
		return fmt.Sprintf("%v", results[0])
	}
	b, _ := json.Marshal(results)
	return string(b)
}

func _steleEvalJsonPath(data any, path string) []any {
	if path == "" {
		return []any{data}
	}
	tokens := _steleTokenizePath(path)
	if len(tokens) == 0 {
		return []any{data}
	}
	kind, value := tokens[0]
	rest := _steleDetokenize(tokens[1:])
	switch kind {
	case "field":
		if m, ok := data.(map[string]any); ok {
			if v, exists := m[value.(string)]; exists {
				return _steleEvalJsonPath(v, rest)
			}
		}
		return nil
	case "index":
		if arr, ok := data.([]any); ok {
			idx := value.(int)
			if idx >= 0 && idx < len(arr) {
				return _steleEvalJsonPath(arr[idx], rest)
			}
		}
		return nil
	case "wildcard":
		if arr, ok := data.([]any); ok {
			var all []any
			for _, item := range arr {
				all = append(all, _steleEvalJsonPath(item, rest)...)
			}
			return all
		}
		return nil
	}
	return nil
}

type _JsonPathToken struct {
	kind  string
	value any
}

func _steleTokenizePath(path string) []_JsonPathToken {
	var tokens []_JsonPathToken
	i := 0
	for i < len(path) {
		if path[i] == '.' {
			i++
			continue
		}
		if path[i] == '[' {
			j := strings.Index(path[i:], "]")
			if j == -1 {
				panic("json-path: unclosed bracket in path")
			}
			j += i
			inner := path[i+1 : j]
			if inner == "*" {
				tokens = append(tokens, _JsonPathToken{kind: "wildcard"})
			} else {
				idx, err := strconv.Atoi(inner)
				if err != nil {
					panic(fmt.Sprintf("json-path: invalid array index: %q", inner))
				}
				tokens = append(tokens, _JsonPathToken{kind: "index", value: idx})
			}
			i = j + 1
			continue
		}
		start := i
		for i < len(path) && path[i] != '.' && path[i] != '[' {
			i++
		}
		name := path[start:i]
		if name != "" {
			tokens = append(tokens, _JsonPathToken{kind: "field", value: name})
		}
	}
	return tokens
}

func _steleDetokenize(tokens []_JsonPathToken) string {
	var sb strings.Builder
	for _, t := range tokens {
		switch t.kind {
		case "field":
			sb.WriteString(".")
			sb.WriteString(t.value.(string))
		case "index":
			sb.WriteString("[")
			sb.WriteString(strconv.Itoa(t.value.(int)))
			sb.WriteString("]")
		case "wildcard":
			sb.WriteString("[*]")
		}
	}
	return sb.String()
}

// steleDecimalEq compares two numbers with exact decimal precision.
func steleDecimalEq(left any, right any) bool {
	l, ok := left.(float64)
	if !ok {
		panic(fmt.Sprintf("decimal-eq: left must be a number, got %T", left))
	}
	r, ok := right.(float64)
	if !ok {
		panic(fmt.Sprintf("decimal-eq: right must be a number, got %T", right))
	}
	lStr := formatDecimal(l)
	rStr := formatDecimal(r)
	return lStr == rStr
}

func formatDecimal(v float64) string {
	if v == float64(int64(v)) {
		return strconv.FormatInt(int64(v), 10)
	}
	s := strconv.FormatFloat(v, 'f', 20, 64)
	// Trim trailing zeros after decimal point.
	if idx := strings.Index(s, "."); idx != -1 {
		s = strings.TrimRight(s, "0")
		s = strings.TrimRight(s, ".")
	}
	return s
}

// ---------------------------------------------------------------------------
// Collection operators
// ---------------------------------------------------------------------------

func steleLength(coll any) int {
	items := asCollection(coll, "length")
	return len(items)
}

func steleConcat(collections ...any) []any {
	if len(collections) < 1 {
		panic("concat: expected at least one collection")
	}
	out := []any{}
	for i, c := range collections {
		items := asCollection(c, fmt.Sprintf("concat[%d]", i))
		out = append(out, items...)
	}
	return out
}

// ---------------------------------------------------------------------------
// Data access
// ---------------------------------------------------------------------------

func steleTypeOf(value any) string {
	if value == nil {
		return "null"
	}
	switch value.(type) {
	case int, int8, int16, int32, int64, uint, uint8, uint16, uint32, uint64, float32, float64:
		return "number"
	case string:
		return "string"
	case bool:
		return "boolean"
	case []any:
		return "collection"
	default:
		return "object"
	}
}

// ---------------------------------------------------------------------------
// Control operators
// ---------------------------------------------------------------------------

func steleNotNull(value any) bool {
	return value != nil
}

func steleBetween(value, low, high any) bool {
	v := toFloat(value, "between")
	lo := toFloat(low, "between")
	hi := toFloat(high, "between")
	return lo <= v && v <= hi
}

func steleApproxEq(a, b, tolerance any) bool {
	left := toFloat(a, "approx-eq")
	right := toFloat(b, "approx-eq")
	tol := toFloat(tolerance, "approx-eq")
	return math.Abs(left-right) <= tol
}

// ---------------------------------------------------------------------------
// steleCompare helper (max-by / min-by)
// ---------------------------------------------------------------------------

// steleCompare returns -1, 0, or 1. Returns error for incomparable types.
func steleCompare(a, b any) (int, error) {
	ai, af, aF, aErr := steleNumeric(a)
	bi, bf, bF, bErr := steleNumeric(b)
	if aErr == nil && bErr == nil {
		if aF || bF {
			if math.Abs(af-bf) < 1e-9 {
				return 0, nil
			}
			if af < bf {
				return -1, nil
			}
			return 1, nil
		}
		if ai < bi {
			return -1, nil
		}
		if ai > bi {
			return 1, nil
		}
		return 0, nil
	}
	// string
	if as, ok := a.(string); ok {
		if bs, ok := b.(string); ok {
			return strings.Compare(as, bs), nil
		}
	}
	return 0, fmt.Errorf("cannot compare %T and %T", a, b)
}

// ---------------------------------------------------------------------------
// Collection transformations (sort-by, sort-by-desc, map, first, last)
// ---------------------------------------------------------------------------

func steleSortBy(coll []any, path []string) []any {
	result := make([]any, len(coll))
	copy(result, coll)
	sort.SliceStable(result, func(i, j int) bool {
		a, aErr := steleGetPath(result[i], path)
		b, bErr := steleGetPath(result[j], path)
		if aErr != nil || bErr != nil {
			return false
		}
		cmp, err := steleCompare(a, b)
		if err != nil {
			return false
		}
		return cmp < 0
	})
	return result
}

func steleSortByDesc(coll []any, path []string) []any {
	result := make([]any, len(coll))
	copy(result, coll)
	sort.SliceStable(result, func(i, j int) bool {
		a, aErr := steleGetPath(result[i], path)
		b, bErr := steleGetPath(result[j], path)
		if aErr != nil || bErr != nil {
			return false
		}
		cmp, err := steleCompare(a, b)
		if err != nil {
			return false
		}
		return cmp > 0
	})
	return result
}

func steleMap(coll []any, path []string) []any {
	result := make([]any, len(coll))
	for i, item := range coll {
		val, err := steleGetPath(item, path)
		if err != nil {
			panic(fmt.Sprintf("map: projection failed at index %d: %v", i, err))
		}
		result[i] = val
	}
	return result
}

func steleFirst(coll []any) any {
	if len(coll) == 0 {
		return nil
	}
	return coll[0]
}

func steleLast(coll []any) any {
	if len(coll) == 0 {
		return nil
	}
	return coll[len(coll)-1]
}

// ---------------------------------------------------------------------------
// Quantifiers (forall / exists / where / none)
// ---------------------------------------------------------------------------

func steleForall(t *testing.T, coll []any, pred func(any) bool, predSource string) error {
	for i, item := range coll {
		if !pred(item) {
			idx := i
			w := FailureWitness{
				Operator:        "forall",
				CollectionSize:  len(coll),
				FailedAtIndex:   &idx,
				FailedItem:      item,
				PredicateSource: predSource,
			}
			emitWitness(t, &w)
			return &SteleAssertionError{
				Message:  fmt.Sprintf("forall failed at index %d", i),
				Witness:  w,
				TestName: t.Name(),
			}
		}
	}
	return nil
}

func steleExists(t *testing.T, coll []any, pred func(any) bool, predSource string) error {
	for i, item := range coll {
		if pred(item) {
			return nil
		}
		_ = i
	}
	// No element satisfies.
	w := FailureWitness{
		Operator:        "exists",
		CollectionSize:  len(coll),
		PredicateSource: predSource,
	}
	if t != nil {
		emitWitness(t, &w)
	}
	return &SteleAssertionError{
		Message:  fmt.Sprintf("exists failed: no element in collection of size %d satisfies predicate", len(coll)),
		Witness:  w,
		TestName: t.Name(),
	}
}

func steleWhere(t *testing.T, coll []any, pred func(any) bool, predSource string) ([]any, error) {
	matched := []any{}
	for _, item := range coll {
		if pred(item) {
			matched = append(matched, item)
		}
	}
	return matched, nil
}

func steleNone(t *testing.T, coll []any, pred func(any) bool, predSource string) error {
	for i, item := range coll {
		if pred(item) {
			idx := i
			w := FailureWitness{
				Operator:        "none",
				CollectionSize:  len(coll),
				FailedAtIndex:   &idx,
				FailedItem:      item,
				PredicateSource: predSource,
			}
			emitWitness(t, &w)
			return &SteleAssertionError{
				Message:  fmt.Sprintf("none failed at index %d: predicate matched an element that should not match", i),
				Witness:  w,
				TestName: t.Name(),
			}
		}
	}
	return nil
}

// ---------------------------------------------------------------------------
// Temporal operators
// ---------------------------------------------------------------------------

func steleIsModified(ctx *SteleContext, segments []string) bool {
	before := ctx.Before
	after := ctx.After
	if before == nil || after == nil {
		panic("modified: state-before or state-after not set on context")
	}
	beforeVal := steleReadPath(before.Data, segments)
	afterVal := steleReadPath(after.Data, segments)
	if beforeVal == nil && afterVal == nil {
		return false
	}
	if beforeVal == nil || afterVal == nil {
		return true
	}
	return !steleEq(beforeVal, afterVal)
}

func steleStateBefore(ctx *SteleContext) *SteleContext {
	if ctx.Before == nil {
		panic("state-before: missing state-before on context")
	}
	return ctx.Before
}

func steleStateAfter(ctx *SteleContext) *SteleContext {
	if ctx.After == nil {
		panic("state-after: missing state-after on context")
	}
	return ctx.After
}

func steleWithin(eventSeconds, durationSeconds, now any) bool {
	event := toFloat(eventSeconds, "within")
	duration := toFloat(durationSeconds, "within")
	n := toFloat(now, "within")
	return event+duration > n
}

func steleBefore(left, right any) bool {
	return toFloat(left, "before") < toFloat(right, "before")
}

func steleAfter(left, right any) bool {
	return toFloat(left, "after") > toFloat(right, "after")
}

// ---------------------------------------------------------------------------
// Path access
// ---------------------------------------------------------------------------

// steleGetPath navigates a path through nested maps. Supports kebab -> snake
// fallback for idiomatic Go naming conventions.
func steleGetPath(obj any, segments []string) (any, error) {
	current := obj
	for _, seg := range segments {
		m, ok := current.(map[string]any)
		if !ok {
			return nil, fmt.Errorf("path navigation hit non-map at %q (got %T)", seg, current)
		}
		if v, hit := m[seg]; hit {
			current = v
			continue
		}
		// kebab -> snake fallback
		snake := strings.ReplaceAll(seg, "-", "_")
		if v, hit := m[snake]; hit {
			current = v
			continue
		}
		return nil, fmt.Errorf("path not found: %q on map keys %v", seg, mapKeys(m))
	}
	return current, nil
}

// steleGetPathVal is a wrapper that calls steleGetPath and panics on error.
// Used by generated test code where a single-return-value helper is needed.
func steleGetPathVal(obj any, segments []string) any {
	v, err := steleGetPath(obj, segments)
	if err != nil {
		panic(err)
	}
	return v
}

// steleReadPath is a variant of steleGetPath that returns nil instead of error
// for missing paths. Used by steleIsModified.
func steleReadPath(data map[string]any, segments []string) any {
	current := any(data)
	for _, seg := range segments {
		m, ok := current.(map[string]any)
		if !ok {
			return nil
		}
		if v, hit := m[seg]; hit {
			current = v
			continue
		}
		snake := strings.ReplaceAll(seg, "-", "_")
		if v, hit := m[snake]; hit {
			current = v
			continue
		}
		return nil
	}
	return current
}

// mapKeys returns all keys in a map, sorted for deterministic error output.
func mapKeys(m map[string]any) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}

// ---------------------------------------------------------------------------
// Checker invocation
// ---------------------------------------------------------------------------

func steleCallChecker(name string, args []any, ctx *SteleContext) (CheckerResult, error) {
	fn, ok := ctx.Checkers[name]
	if !ok {
		return CheckerResult{}, fmt.Errorf("checker %q not registered", name)
	}
	return fn(args, ctx), nil
}

// ---------------------------------------------------------------------------
// Scenario runtime
// ---------------------------------------------------------------------------

func steleRunScenario(steps []ScenarioStep, ctx *SteleContext) (*SteleContext, error) {
	current := new(SteleContext)
	current.Data = make(map[string]any)
	current.Checkers = make(map[string]CheckerFunc)
	// Copy from parent context.
	for k, v := range ctx.Data {
		current.Data[k] = v
	}
	for _, step := range steps {
		_ = step
		// Step execution would invoke the target function.
		// In the generated code, the user provides the execution logic.
	}
	return current, nil
}

// ---------------------------------------------------------------------------
// Context merging
// ---------------------------------------------------------------------------

func steleMergeContexts(contexts ...*SteleContext) *SteleContext {
	merged := NewContext()
	for _, ctx := range contexts {
		if ctx == nil {
			continue
		}
		for k, v := range ctx.Data {
			merged.Data[k] = v
		}
		for k, v := range ctx.Checkers {
			merged.Checkers[k] = v
		}
	}
	return merged
}

// ---------------------------------------------------------------------------
// steleToInterfaceSlice helper
// ---------------------------------------------------------------------------

// steleToInterfaceSlice converts any slice to []interface{}.
func steleToInterfaceSlice(v any) []any {
	val := reflect.ValueOf(v)
	if val.Kind() != reflect.Slice {
		return []any{v}
	}
	result := make([]any, val.Len())
	for i := 0; i < val.Len(); i++ {
		elem := val.Index(i)
		if !elem.CanInterface() {
			cpy := reflect.New(elem.Type()).Elem()
			cpy.Set(elem)
			result[i] = cpy.Interface()
		} else {
			result[i] = elem.Interface()
		}
	}
	return result
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

func asCollection(coll any, op string) []any {
	items, ok := coll.([]any)
	if !ok {
		panic(fmt.Sprintf("%s: expected []interface{}, got %T", op, coll))
	}
	return items
}

func projectCollection(items []any, segments []string) []any {
	if len(segments) == 0 {
		out := make([]any, len(items))
		copy(out, items)
		return out
	}
	result := make([]any, len(items))
	for i, item := range items {
		val, err := steleGetPath(item, segments)
		if err != nil {
			panic(fmt.Sprintf("projection failed at index %d: %v", i, err))
		}
		result[i] = val
	}
	return result
}

func canonicalKey(value any) string {
	if value == nil {
		return "n:null"
	}
	switch v := value.(type) {
	case string:
		return "s:" + v
	case int, int8, int16, int32, int64, uint, uint8, uint16, uint32, uint64, float32, float64:
		return "#:" + fmt.Sprint(v)
	case bool:
		return "b:" + fmt.Sprint(v)
	default:
		data, _ := json.Marshal(value)
		return "j:" + string(data)
	}
}

// steleAssertTrue asserts a condition is true, failing the test if not.
func steleAssertTrue(t *testing.T, cond bool, msg string) {
	t.Helper()
	if !cond {
		t.Errorf("%s", msg)
		t.FailNow()
	}
}

// ---------------------------------------------------------------------------
// Assert helper for generated tests (steleAssertTrue alias)
// ---------------------------------------------------------------------------

// _ is a sentinel to suppress "unused import" errors when helpers are not
// referenced by generated code in a given run.
var _ = steleAssertTrue

// ---------------------------------------------------------------------------
// Global context for generated test functions
// ---------------------------------------------------------------------------

// globalCtx is the default context used by generated invariant test functions.
// It is initialized in init() to a safe default. Override it in TestMain or
// setup_test.go with SetupSteleContext() to provide real data.
var globalCtx *SteleContext

func init() {
	if globalCtx == nil {
		globalCtx = NewContext()
	}
}
