import { posix } from "node:path";
import { writeFile } from "node:fs/promises";
import type { LanguageBackend } from "@stele/core";
import { getGoRuntimeSource } from "./runtime.js";
import { generateGoTestSource, sanitizeGoIdentifier } from "./translator.js";
import { writeFixtureBootstrap } from "./conformance-bootstrap.js";

const backend: LanguageBackend = {
  name: "go",
  framework: "testing",
  fileExtension: ".go",
  version: "0.1.0",
  generate(contract, config) {
    const generatedDir = config.outputDir ?? "tests/contract";
    const files = [
      {
        path: posix.join(generatedDir, "stele_runtime_test.go"),
        content: getGoRuntimeSource(),
      },
    ];

    const topLevelInvariants = contract.invariants.filter((invariant) => invariant.groupId === undefined);

    if (topLevelInvariants.length > 0) {
      files.push({
        path: posix.join(generatedDir, "test_contract_test.go"),
        content: generateGoTestSource({
          ...contract,
          invariants: topLevelInvariants,
        }),
      });
    }

    for (const group of contract.groups) {
      files.push({
        path: posix.join(generatedDir, `test_${sanitizeGoIdentifier(group.id, "group")}_test.go`),
        content: generateGoTestSource({
          ...contract,
          invariants: group.invariants,
        }),
      });
    }

    return files;
  },
  supportFiles(_contract, config) {
    const generatedDir = config.outputDir ?? "tests/contract";
    return [
      {
        path: posix.join(generatedDir, "stele_setup_test.go"),
        content: GO_SETUP_TEMPLATE,
      },
    ];
  },
  async writeFixtureBootstrap(fixture, tmpdir) {
    const generatedFile = writeFixtureBootstrap(fixture);
    const outputPath = posix.join(tmpdir, generatedFile.name);
    await writeFile(outputPath, generatedFile.content, "utf8");
  },
};

/**
 * Template for setup_test.go that users fill in.
 * Matches design doc §8.2: user writes SetupSteleContext() but NOT TestMain.
 */
const GO_SETUP_TEMPLATE = `// setup_test.go (user-owned; fill in your data setup)
// Generated by Stele — edit this file to wire your application data.

package contract_test

// SetupSteleContext initializes the SteleContext with your application data.
// Edit this function to populate ctx.Data with the data your invariants need.
func SetupSteleContext() *SteleContext {
	ctx := NewContext()

	// Example: load your application state into the context.
	// ctx.Data["account"] = steleToInterfaceSlice(ledger.AccountSnapshot())
	// ctx.Data["positions"] = steleToInterfaceSlice(ledger.LoadOpenPositions())

	// Example: register a custom checker.
	// ctx.RegisterChecker("my-checker", func(args []any, c *SteleContext) CheckerResult {
	//     return CheckerResult{Ok: true}
	// })

	return ctx
}
`;

export { backend };
export default backend;
